// src/assets/examples/reactive-form-validators/template-driven/validation-directives/alpha/messageKey/alpha-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { AddressInfo } from './address-info.model';

@Component({
    selector: 'app-alpha-messageKey-template-driven-validation-directives',
    templateUrl: './alpha-message-key.component.html'
})
export class AlphaMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    addressinfo: AddressInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.addressinfo= new AddressInfo()
    }
}

<div>
  <form #addressinfoForm = "ngForm" [rxwebForm]="addressinfoForm" [model]="addressinfo">
    <div class="form-group">
      <label>City Code</label>
	    <input type="text" name="cityCode" [(ngModel)]="addressinfo.cityCode"  class="form-control" [rxalpha]="{'messageKey':'alphaMessageKey'}"/>

      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	   <small class="form-text text-danger" *ngIf="addressinfoForm.controls?.cityCode?.errors">{{addressinfoForm.controls?.cityCode?.errors?.alpha.message}}<br/></small>	
    </div>
    <button [disabled]="!addressinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/alpha/messageKey/alpha-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>City Code</label>
        <input id="name" class="form-control" v-model="addressInfoFormGroup.props.cityCode" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="addressInfoFormGroup.controls.cityCode.errors">
         <small class="form-text text-danger">{{addressInfoFormGroup.controls.cityCode.errors.alpha.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AddressInfo } from './addressInfo.model';

@Component
export default class AlphaMessageKeyComponent extends Vue {
 addressInfoFormGroup: IFormGroup<AddressInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.addressInfoFormGroup = this.formBuilder.formGroup(AddressInfo) as IFormGroup<AddressInfo>;
   }
}
</script>
