// Examples/vue/rxweb-reactive-forms/src/components/longitude/dynamic/longitude-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label> Continent</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.continent" type="text" name="name" />
        <div v-if="countryFormGroup.controls.continent.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.continent.errors.longitude.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Second Country Longitude</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.secondCountryLongitude" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Second Country Longitude' then you need to add 'Continent' input as 'Asia'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="countryFormGroup.controls.secondCountryLongitude.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.secondCountryLongitude.errors.longitude.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Third Country Longitude</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.thirdCountryLongitude" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Third Country Longitude' then you need to add 'Continent' input as 'Asia'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="countryFormGroup.controls.thirdCountryLongitude.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.thirdCountryLongitude.errors.longitude.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>First Country Longitude</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.firstCountryLongitude" type="text" name="name" />
          <small class="form-text text-muted">You can enter only longitude<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="countryFormGroup.controls.firstCountryLongitude.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.firstCountryLongitude.errors.longitude.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Fourth Country Longitude</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.fourthCountryLongitude" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="countryFormGroup.controls.fourthCountryLongitude.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.fourthCountryLongitude.errors.longitude.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Country } from './country.model';

@Component
export default class LongitudeDynamicComponent extends Vue {
 countryFormGroup: IFormGroup<Country>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.countryFormGroup = this.formBuilder.formGroup(Country) as IFormGroup<Country>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/longitude/dynamic/longitude-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';
import { FormBuilderConfiguration,} from '@rxweb/reactive-form-validators';

import { Country } from './country.model';

@Component({
    selector: 'app-longitude-dynamic',
    templateUrl: './longitude-dynamic.component.html'
})
export class LongitudeDynamicComponent implements OnInit {
    countryFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        let country = new Country();
        let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/longitude/dynamic/dynamic.json?v=' + environment.appVersion).subscribe(dynamic => {
            formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			this.countryFormGroup = this.formBuilder.formGroup(country,formBuilderConfiguration);
        })
    }
}

<div>
  <form  *ngIf="countryFormGroup"  [formGroup]="countryFormGroup">
    <div class="form-group">
      <label> Continent</label>
      <input type="text" formControlName="continent" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Second Country Longitude' or 'Third Country Longitude', then you need to add 'Continent' input as 'Asia'.<br/></small>
      <small class="form-text text-danger" *ngIf="countryFormGroup.controls.continent.errors">{{countryFormGroup.controls.continent.errors.longitude.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Third Country Longitude</label>
      <input type="text" formControlName="thirdCountryLongitude" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Third Country Longitude' then you need to add 'Continent' input as 'Asia'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.thirdCountryLongitude.errors">{{countryFormGroup.controls.thirdCountryLongitude.errors.longitude.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>First Country Longitude</label>
      <input type="text" formControlName="firstCountryLongitude" class="form-control"  />
      <small class="form-text text-muted">You can enter only longitude<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.firstCountryLongitude.errors">{{countryFormGroup.controls.firstCountryLongitude.errors.longitude.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Fourth Country Longitude</label>
      <input type="text" formControlName="fourthCountryLongitude" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.fourthCountryLongitude.errors">{{countryFormGroup.controls.fourthCountryLongitude.errors.longitude.message}}<br/></small>
    </div>
    <button [disabled]="!countryFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
