// Examples/vue/rxweb-reactive-forms/src/components/notEmpty/complete/not-empty-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>First Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.firstName" type="text" name="name" />
        <div v-if="userFormGroup.controls.firstName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.firstName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Middle Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.middleName" type="text" name="name" />
          <small class="form-text text-muted">Conditional validation will be applied if the user enter 'Bharat' in 'FirstName' field <br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.middleName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.middleName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Last Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.lastName" type="text" name="name" />
          <small class="form-text text-muted">Conditional validation will be applied if the user enter 'Bharat' in 'First Name' field <br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.lastName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.lastName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>UserName</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.userName" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
       <div v-if="userFormGroup.controls.userName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.userName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Full Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.fullName" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message based on message key<br/></small>
       <div v-if="userFormGroup.controls.fullName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.fullName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class NotEmptyCompleteComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/template-driven/validation-directives/notEmpty/complete/not-empty-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-notEmpty-complete-template-driven-validation-directives',
    templateUrl: './not-empty-complete.component.html'
})
export class NotEmptyCompleteTemplateDrivenValidationDirectivesComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>First Name</label>
	    <input type="text" name="firstName" [(ngModel)]="user.firstName"  class="form-control" rxnotEmpty/>

	   <small class="form-text text-danger" *ngIf="userForm.controls?.firstName?.errors">{{userForm.controls?.firstName?.errors?.notEmpty.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Last Name</label>
	    <input type="text" name="lastName" [(ngModel)]="user.lastName"  class="form-control" [rxnotEmpty]="{'conditionalExpression':'x => x.firstName == \'Bharat\''}"/>

      <small class="form-text text-muted">Conditional validation will be applied if the user enter 'Bharat' in 'First Name' field <br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.lastName?.errors">{{userForm.controls?.lastName?.errors?.notEmpty.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>UserName</label>
	    <input type="text" name="userName" [(ngModel)]="user.userName"  class="form-control" [rxnotEmpty]="{'message':'Username cannot be blank.'}"/>

      <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.userName?.errors">{{userForm.controls?.userName?.errors?.notEmpty.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Full Name</label>
	    <input type="text" name="fullName" [(ngModel)]="user.fullName"  class="form-control" [rxnotEmpty]="{'messageKey':'notEmptyMessageKey'}"/>

      <small class="form-text text-muted">Shows Custom Validation Message based on message key<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.fullName?.errors">{{userForm.controls?.fullName?.errors?.notEmpty.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
