// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/decorators/minLength/edit/min-length-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { Contact } from './contact.model';

@Component({
    selector: 'app-minLength-edit',
    templateUrl: './min-length-edit.component.html'
})
export class MinLengthEditComponent implements OnInit {
    contactFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/minLength/edit/contact-data.json?v=' + environment.appVersion).subscribe(contact => {
            this.contactFormGroup = this.formBuilder.formGroup<Contact>(Contact,contact);
        })
    }
}

<div>
  <form  *ngIf="contactFormGroup"  [formGroup]="contactFormGroup">
    <div class="form-group">
      <label>Country Name</label>
      <input type="text" formControlName="countryName" class="form-control"  />
      <small class="form-text text-muted">Minimum length upto 3 characters.<br/></small>
	<small class="form-text text-danger" *ngIf="contactFormGroup.controls.countryName.errors">{{contactFormGroup.controls.countryName.errors.minLength.message}}<br/></small>
    </div>
    <button [disabled]="!contactFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/minLength/edit/min-length-edit.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Country Name</label>
        <input id="name" class="form-control" v-model="contactFormGroup.props.countryName" type="text" name="name" />
          <small class="form-text text-muted">Minimum length upto 3 characters.<br/></small>
       <div v-if="contactFormGroup.controls.countryName.errors">
         <small class="form-text text-danger">{{contactFormGroup.controls.countryName.errors.minLength.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Contact } from './contact.model';

@Component
export default class MinLengthEditComponent extends Vue {
 contactFormGroup: IFormGroup<Contact>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.contactFormGroup = this.formBuilder.formGroup(Contact) as IFormGroup<Contact>;
   }
}
</script>
