// Examples/vue/rxweb-reactive-forms/src/components/maxLength/dynamic/max-length-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>First Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.firstName" type="text" name="name" />
        <div v-if="userFormGroup.controls.firstName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.firstName.errors.maxLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Middle Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.middleName" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditionalExpression on 'Middle Name', then enter 'Bharat' in 'First Name'<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.middleName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.middleName.errors.maxLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Last Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.lastName" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditionalExpression on 'Last Name', then enter 'Bharat' in 'First Name'<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.lastName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.lastName.errors.maxLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>User Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.userName" type="text" name="name" />
        <div v-if="userFormGroup.controls.userName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.userName.errors.maxLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Full Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.fullName" type="text" name="name" />
        <div v-if="userFormGroup.controls.fullName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.fullName.errors.maxLength.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class MaxLengthDynamicComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/maxLength/dynamic/max-length-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';
import { FormBuilderConfiguration,} from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-maxLength-dynamic',
    templateUrl: './max-length-dynamic.component.html'
})
export class MaxLengthDynamicComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        let user = new User();
        let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/maxLength/dynamic/dynamic.json?v=' + environment.appVersion).subscribe(dynamic => {
            formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			this.userFormGroup = this.formBuilder.formGroup(user,formBuilderConfiguration);
        })
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>First Name</label>
      <input type="text" formControlName="firstName" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Middle Name' or 'Last name', then you need to add 'First Name' input as 'Bharat'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.firstName.errors">{{userFormGroup.controls.firstName.errors.maxLength.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Last Name</label>
      <input type="text" formControlName="lastName" class="form-control"  />
      <small class="form-text text-muted">To apply the validation of lowerCase on 'Last Name' field, write 'Bharat' in 'First Name' textbox because it is conditional expression. and maximum length is 16<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.lastName.errors">{{userFormGroup.controls.lastName.errors.maxLength.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>User Name</label>
      <input type="text" formControlName="userName" class="form-control"  />
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.userName.errors">{{userFormGroup.controls.userName.errors.maxLength.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Full Name</label>
      <input type="text" formControlName="fullName" class="form-control"  />
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.fullName.errors">{{userFormGroup.controls.fullName.errors.maxLength.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
