// src/assets/examples/reactive-form-validators/validators/upperCase/dynamic/upper-case-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-upperCase-dynamic-validator',
    templateUrl: './upper-case-dynamic.component.html'
})
export class UpperCaseDynamicValidatorComponent implements OnInit {
    locationFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/upperCase/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var location = { countryName:'', stateName:'', cityName:'', colonyName:'', streetName:'',  }
			this.locationFormGroup = this.formBuilder.group(location,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="locationFormGroup"  [formGroup]="locationFormGroup">
    <div class="form-group">
      <label>Country Name</label>
      <input type="text" formControlName="countryName" class="form-control"   />
      <small class="form-text text-muted">Enter the 'INDIA' in 'Country Name' or 'City Name' text box to see the validation in 'State Name' text box.<br/></small>
      <small class="form-text text-danger" *ngIf="locationFormGroup.controls.countryName.errors">{{locationFormGroup.controls.countryName.errors.upperCase.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>City Name</label>
      <input type="text" formControlName="cityName" class="form-control"  />
      <small class="form-text text-muted">To apply the validation of upperCase on 'City Name' field, then enter the value of 'INDIA' in 'Country Name' textbox.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="locationFormGroup.controls.cityName.errors">{{locationFormGroup.controls.cityName.errors.upperCase.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Colony Name</label>
      <input type="text" formControlName="colonyName" class="form-control"  />
	<small class="form-text text-danger" *ngIf="locationFormGroup.controls.colonyName.errors">{{locationFormGroup.controls.colonyName.errors.upperCase.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Street Name</label>
      <input type="text" formControlName="streetName" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="locationFormGroup.controls.streetName.errors">{{locationFormGroup.controls.streetName.errors.upperCase.message}}<br/></small>
    </div>
    <button [disabled]="!locationFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/upperCase/dynamic/upper-case-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Country Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.countryName" type="text" name="name" />
        <div v-if="locationFormGroup.controls.countryName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.countryName.errors.upperCase.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>State Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.stateName" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of upperCase on 'State Name' field, then enter the value of 'INDIA' in 'Country Name' textbox.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="locationFormGroup.controls.stateName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.stateName.errors.upperCase.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>City Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.cityName" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of upperCase on 'City Name' field, then enter the value of 'INDIA' in 'Country Name' textbox.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="locationFormGroup.controls.cityName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.cityName.errors.upperCase.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Colony Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.colonyName" type="text" name="name" />
        <div v-if="locationFormGroup.controls.colonyName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.colonyName.errors.upperCase.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Street Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.streetName" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="locationFormGroup.controls.streetName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.streetName.errors.upperCase.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Location } from './location.model';

@Component
export default class UpperCaseDynamicComponent extends Vue {
 locationFormGroup: IFormGroup<Location>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.locationFormGroup = this.formBuilder.formGroup(Location) as IFormGroup<Location>;
   }
}
</script>
