// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/decorators/toString/add/to-string-add.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-toString-add',
    templateUrl: './to-string-add.component.html'
})
export class ToStringAddComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder
        ) { }

    ngOnInit() {
        let user = new User();
        this.userFormGroup = this.formBuilder.formGroup(user);
    }
}

// Examples/vue/rxweb-reactive-forms/src/components/toString/add/to-string-add.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Free Text</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.freeText" type="text" name="name" />
        <div v-if="userFormGroup.controls.freeText.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.freeText.errors.toString.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class ToStringAddComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
