// src/assets/examples/reactive-form-validators/validators/ascii/complete/ascii-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-ascii-complete-validator',
    templateUrl: './ascii-complete.component.html'
})
export class AsciiCompleteValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            language:['',], 
            numberAsciiCode:['', RxwebValidators.ascii({conditionalExpression:(x,y) => x.language == "Java"  })], 
            alphabetAsciiCode:['', RxwebValidators.ascii({conditionalExpression:'x => x.language =="Java"' })], 
            specialCharAsciiCode:['', RxwebValidators.ascii({message:'{{0}} is not an Ascii Code' })], 
            digitalCode:['', RxwebValidators.ascii({messageKey:'asciiMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Language</label>
      <input type="text" formControlName="language" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Number Ascii Code' or 'Alphabet Ascii Code', then you need to add 'Language' input as 'Java'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.language.errors">{{userFormGroup.controls.language.errors.ascii.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Number Ascii Code</label>
      <input type="text" formControlName="numberAsciiCode" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Number Ascii Code' then you need to add 'Language' input as 'Java'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.numberAsciiCode.errors">{{userFormGroup.controls.numberAsciiCode.errors.ascii.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Alphabet Ascii Code</label>
      <input type="text" formControlName="alphabetAsciiCode" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Alphabet Ascii Code' then you need to add 'Language' input as 'Java'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.alphabetAsciiCode.errors">{{userFormGroup.controls.alphabetAsciiCode.errors.ascii.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Special Character Ascii Code</label>
      <input type="text" formControlName="specialCharAsciiCode" class="form-control"  />
      <small class="form-text text-muted">enter Ascii Code only<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.specialCharAsciiCode.errors">{{userFormGroup.controls.specialCharAsciiCode.errors.ascii.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Digital Code</label>
      <input type="text" formControlName="digitalCode" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.digitalCode.errors">{{userFormGroup.controls.digitalCode.errors.ascii.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/ascii/complete/ascii-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Language</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.language" type="text" name="name" />
        <div v-if="userFormGroup.controls.language.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.language.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Number Ascii Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.numberAsciiCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Number Ascii Code' then you need to add 'Language' input as 'Java'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.numberAsciiCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.numberAsciiCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Alphabet Ascii Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.alphabetAsciiCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Alphabet Ascii Code' then you need to add 'Language' input as 'Java'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.alphabetAsciiCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.alphabetAsciiCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Special Character Ascii Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.specialCharAsciiCode" type="text" name="name" />
          <small class="form-text text-muted">enter Ascii Code only<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.specialCharAsciiCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.specialCharAsciiCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Digital Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.digitalCode" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.digitalCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.digitalCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class AsciiCompleteComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
