// src/assets/examples/reactive-form-validators/validators/latLong/complete/lat-long-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-latLong-complete-validator',
    templateUrl: './lat-long-complete.component.html'
})
export class LatLongCompleteValidatorComponent implements OnInit {
    countryFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.countryFormGroup = this.formBuilder.group({
            continent:['',], 
            secondCountry:['', RxwebValidators.latLong({conditionalExpression:(x,y) => x.continent == "Asia"  })], 
            thirdCountry:['', RxwebValidators.latLong({conditionalExpression:'x => x.continent =="Asia"' })], 
            firstCountry:['', RxwebValidators.latLong({message:'{{0}} is not a proper proper Latitude or Longitude' })], 
            fourthCountry:['', RxwebValidators.latLong({messageKey:'latLongMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="countryFormGroup">
    <div class="form-group">
      <label>Continent</label>
      <input type="text" formControlName="continent" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Second Country' or 'Third Country', then you need to add 'Continent' input as 'Asia'<br/></small>
     <small class="form-text text-danger" *ngIf="countryFormGroup.controls.continent.errors">{{countryFormGroup.controls.continent.errors.latLong.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Second Country</label>
      <input type="text" formControlName="secondCountry" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Second Country' then you need to add 'Continent' input as 'Asia'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.secondCountry.errors">{{countryFormGroup.controls.secondCountry.errors.latLong.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Third Country</label>
      <input type="text" formControlName="thirdCountry" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Third Country' then you need to add 'Continent' input as 'Asia'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.thirdCountry.errors">{{countryFormGroup.controls.thirdCountry.errors.latLong.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>First Country</label>
      <input type="text" formControlName="firstCountry" class="form-control"  />
      <small class="form-text text-muted">enter latitude or longitude only<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.firstCountry.errors">{{countryFormGroup.controls.firstCountry.errors.latLong.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Fourth Country</label>
      <input type="text" formControlName="fourthCountry" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.fourthCountry.errors">{{countryFormGroup.controls.fourthCountry.errors.latLong.message}}<br/></small>
    </div>
    <button [disabled]="!countryFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/latLong/complete/lat-long-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Continent</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.continent" type="text" name="name" />
        <div v-if="countryFormGroup.controls.continent.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.continent.errors.latLong.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Second Country</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.secondCountry" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Second Country' then you need to add 'Continent' input as 'Asia'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="countryFormGroup.controls.secondCountry.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.secondCountry.errors.latLong.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Third Country</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.thirdCountry" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Third Country' then you need to add 'Continent' input as 'Asia'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="countryFormGroup.controls.thirdCountry.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.thirdCountry.errors.latLong.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>First Country</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.firstCountry" type="text" name="name" />
          <small class="form-text text-muted">enter latitude or longitude only<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="countryFormGroup.controls.firstCountry.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.firstCountry.errors.latLong.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Fourth Country</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.fourthCountry" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
       <div v-if="countryFormGroup.controls.fourthCountry.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.fourthCountry.errors.latLong.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Country } from './country.model';

@Component
export default class LatLongCompleteComponent extends Vue {
 countryFormGroup: IFormGroup<Country>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.countryFormGroup = this.formBuilder.formGroup(Country) as IFormGroup<Country>;
   }
}
</script>
