// src/assets/examples/reactive-form-validators/validators/alpha/dynamic/alpha-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-alpha-dynamic-validator',
    templateUrl: './alpha-dynamic.component.html'
})
export class AlphaDynamicValidatorComponent implements OnInit {
    addressInfoFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/alpha/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var addressInfo = { countryName:'', countryCode:'', cityName:'', stateName:'', stateCode:'', cityCode:'',  }
			this.addressInfoFormGroup = this.formBuilder.group(addressInfo,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="addressInfoFormGroup"  [formGroup]="addressInfoFormGroup">
    <div class="form-group">
      <label>Country Name</label>
      <input type="text" formControlName="countryName" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Country Code' or 'City' then you need to add this input as 'India'.<br/></small>
      <small class="form-text text-danger" *ngIf="addressInfoFormGroup.controls.countryName.errors">{{addressInfoFormGroup.controls.countryName.errors.alpha.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>City</label>
      <input type="text" formControlName="cityName" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'City' then you need to add 'Country Name' input as 'India'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="addressInfoFormGroup.controls.cityName.errors">{{addressInfoFormGroup.controls.cityName.errors.alpha.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>State Name</label>
      <input type="text" formControlName="stateName" class="form-control"  />
      <small class="form-text text-muted">This allowed whitespace in alpha validation<br/></small>
	<small class="form-text text-danger" *ngIf="addressInfoFormGroup.controls.stateName.errors">{{addressInfoFormGroup.controls.stateName.errors.alpha.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>State Code</label>
      <input type="text" formControlName="stateCode" class="form-control"  />
      <small class="form-text text-muted">Shows custom message<br/></small>
	<small class="form-text text-danger" *ngIf="addressInfoFormGroup.controls.stateCode.errors">{{addressInfoFormGroup.controls.stateCode.errors.alpha.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>City Code</label>
      <input type="text" formControlName="cityCode" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="addressInfoFormGroup.controls.cityCode.errors">{{addressInfoFormGroup.controls.cityCode.errors.alpha.message}}<br/></small>
    </div>
    <button [disabled]="!addressInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/alpha/dynamic/alpha-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Country Name</label>
        <input id="name" class="form-control" v-model="addressInfoFormGroup.props.countryName" type="text" name="name" />
        <div v-if="addressInfoFormGroup.controls.countryName.errors">
         <small class="form-text text-danger">{{addressInfoFormGroup.controls.countryName.errors.alpha.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Country Code</label>
        <input id="name" class="form-control" v-model="addressInfoFormGroup.props.countryCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Country Code' then you need to add 'Country Name' input as 'India'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="addressInfoFormGroup.controls.countryCode.errors">
         <small class="form-text text-danger">{{addressInfoFormGroup.controls.countryCode.errors.alpha.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>City</label>
        <input id="name" class="form-control" v-model="addressInfoFormGroup.props.cityName" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'City' then you need to add 'Country Name' input as 'India'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="addressInfoFormGroup.controls.cityName.errors">
         <small class="form-text text-danger">{{addressInfoFormGroup.controls.cityName.errors.alpha.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>State Name</label>
        <input id="name" class="form-control" v-model="addressInfoFormGroup.props.stateName" type="text" name="name" />
          <small class="form-text text-muted">This allowed whitespace in alpha validation<br/></small>
       <div v-if="addressInfoFormGroup.controls.stateName.errors">
         <small class="form-text text-danger">{{addressInfoFormGroup.controls.stateName.errors.alpha.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>State Code</label>
        <input id="name" class="form-control" v-model="addressInfoFormGroup.props.stateCode" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="addressInfoFormGroup.controls.stateCode.errors">
         <small class="form-text text-danger">{{addressInfoFormGroup.controls.stateCode.errors.alpha.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>City Code</label>
        <input id="name" class="form-control" v-model="addressInfoFormGroup.props.cityCode" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="addressInfoFormGroup.controls.cityCode.errors">
         <small class="form-text text-danger">{{addressInfoFormGroup.controls.cityCode.errors.alpha.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AddressInfo } from './addressInfo.model';

@Component
export default class AlphaDynamicComponent extends Vue {
 addressInfoFormGroup: IFormGroup<AddressInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.addressInfoFormGroup = this.formBuilder.formGroup(AddressInfo) as IFormGroup<AddressInfo>;
   }
}
</script>
