// src/assets/examples/reactive-form-validators/validators/dataUri/dynamic/data-uri-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-dataUri-dynamic-validator',
    templateUrl: './data-uri-dynamic.component.html'
})
export class DataUriDynamicValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/dataUri/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var user = { scheme:'', imageDataUri:'', audioDataUri:'', videoDataUri:'', pdfDataUri:'',  }
			this.userFormGroup = this.formBuilder.group(user,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Scheme</label>
      <input type="text" formControlName="scheme" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Image Data Uri' or 'Audio Data Uri', then you need to add 'Scheme' input as 'DataUri'<br/></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.scheme.errors">{{userFormGroup.controls.scheme.errors.dataUri.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Audio Data Uri</label>
      <input type="text" formControlName="audioDataUri" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Audio Data Uri' then you need to add 'Scheme' input as 'DataUri'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.audioDataUri.errors">{{userFormGroup.controls.audioDataUri.errors.dataUri.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Video Data Uri</label>
      <input type="text" formControlName="videoDataUri" class="form-control"  />
      <small class="form-text text-muted">enter Data URI only<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.videoDataUri.errors">{{userFormGroup.controls.videoDataUri.errors.dataUri.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Pdf Data Uri</label>
      <input type="text" formControlName="pdfDataUri" class="form-control"  />
      <small class="form-text text-muted">Custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.pdfDataUri.errors">{{userFormGroup.controls.pdfDataUri.errors.dataUri.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/dataUri/dynamic/data-uri-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Scheme</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.scheme" type="text" name="name" />
        <div v-if="userFormGroup.controls.scheme.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.scheme.errors.dataUri.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Image Data Uri</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.imageDataUri" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Image Data Uri' then you need to add 'Scheme' input as 'DataUri'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.imageDataUri.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.imageDataUri.errors.dataUri.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Audio Data Uri</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.audioDataUri" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Audio Data Uri' then you need to add 'Scheme' input as 'DataUri'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.audioDataUri.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.audioDataUri.errors.dataUri.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Video Data Uri</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.videoDataUri" type="text" name="name" />
          <small class="form-text text-muted">enter Data URI only<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.videoDataUri.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.videoDataUri.errors.dataUri.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Pdf Data Uri</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.pdfDataUri" type="text" name="name" />
          <small class="form-text text-muted">Custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.pdfDataUri.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.pdfDataUri.errors.dataUri.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class DataUriDynamicComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
