// Examples/vue/rxweb-reactive-forms/src/components/longitude/edit/longitude-edit.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>First Country Longitude</label>
        <input id="name" class="form-control" v-model="numberInfoFormGroup.props.firstCountryLongitude" type="text" name="name" />
          <small class="form-text text-muted">You must enter a valid longitude<br/></small>
       <div v-if="numberInfoFormGroup.controls.firstCountryLongitude.errors">
         <small class="form-text text-danger">{{numberInfoFormGroup.controls.firstCountryLongitude.errors.longitude.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { NumberInfo } from './numberInfo.model';

@Component
export default class LongitudeEditComponent extends Vue {
 numberInfoFormGroup: IFormGroup<NumberInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.numberInfoFormGroup = this.formBuilder.formGroup(NumberInfo) as IFormGroup<NumberInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/longitude/edit/longitude-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { NumberInfo } from './number-info.model';

@Component({
    selector: 'app-longitude-edit',
    templateUrl: './longitude-edit.component.html'
})
export class LongitudeEditComponent implements OnInit {
    numberInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/longitude/edit/number-info-data.json?v=' + environment.appVersion).subscribe(numberInfo => {
            this.numberInfoFormGroup = this.formBuilder.formGroup<NumberInfo>(NumberInfo,numberInfo);
        })
    }
}

<div>
  <form  *ngIf="numberInfoFormGroup"  [formGroup]="numberInfoFormGroup">
    <div class="form-group">
      <label>First Country Longitude</label>
      <input type="text" formControlName="firstCountryLongitude" class="form-control"  />
      <small class="form-text text-muted">You must enter a valid longitude<br/></small>
     <small class="form-text text-danger" *ngIf="numberInfoFormGroup.controls.firstCountryLongitude.errors">{{numberInfoFormGroup.controls.firstCountryLongitude.errors.longitude.message}}<br/></small>	
    </div>
    <button [disabled]="!numberInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
