// src/assets/examples/reactive-form-validators/template-driven/validation-directives/grid/messageKey/grid-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { DigitalInfo } from './digital-info.model';

@Component({
    selector: 'app-grid-messageKey-template-driven-validation-directives',
    templateUrl: './grid-message-key.component.html'
})
export class GridMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    digitalinfo: DigitalInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.digitalinfo= new DigitalInfo()
    }
}

<div>
  <form #digitalinfoForm = "ngForm" [rxwebForm]="digitalinfoForm" [model]="digitalinfo">
    <div class="form-group">
      <label>VideoGraphic GRid</label>
	    <input type="text" name="videoGraphicGrid" [(ngModel)]="digitalinfo.videoGraphicGrid"  class="form-control" [grid]="{'messageKey':'gridMessageKey'}"/>

      <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
	   <small class="form-text text-danger" *ngIf="digitalinfoForm.controls?.videoGraphicGrid?.errors">{{digitalinfoForm.controls?.videoGraphicGrid?.errors?.grid.message}}<br/></small>	
    </div>
    <button [disabled]="!digitalinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/grid/messageKey/grid-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>VideoGraphic GRid</label>
        <input id="name" class="form-control" v-model="digitalInfoFormGroup.props.videoGraphicGrid" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
       <div v-if="digitalInfoFormGroup.controls.videoGraphicGrid.errors">
         <small class="form-text text-danger">{{digitalInfoFormGroup.controls.videoGraphicGrid.errors.grid.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { DigitalInfo } from './digitalInfo.model';

@Component
export default class GridMessageKeyComponent extends Vue {
 digitalInfoFormGroup: IFormGroup<DigitalInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.digitalInfoFormGroup = this.formBuilder.formGroup(DigitalInfo) as IFormGroup<DigitalInfo>;
   }
}
</script>
