// Examples/vue/rxweb-reactive-forms/src/components/lessThan/complete/less-than-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Obtained Marks</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.obtainedMarks" type="text" name="name" />
        <div v-if="userFormGroup.controls.obtainedMarks.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.obtainedMarks.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Other Activity Marks</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherActivityMarks" type="text" name="name" />
          <small class="form-text text-muted">Other Activity Marks less than to Obtained marks<br/></small>
       <div v-if="userFormGroup.controls.otherActivityMarks.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherActivityMarks.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Maximum Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.maximumAge" type="text" name="name" />
        <div v-if="userFormGroup.controls.maximumAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.maximumAge.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Practical Exam Marks</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.practicalExamMarks" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation of less than validation on 'Practical Exam Marks' then Obtained Marks must be less than '35'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.practicalExamMarks.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.practicalExamMarks.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Passing Marks</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.passingMarks" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Passing Marks' then you need to add 'Obtained Marks' field less than '35'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.passingMarks.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.passingMarks.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Other Marks</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherMarks" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="userFormGroup.controls.otherMarks.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherMarks.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Discipline Marks</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.disciplineMarks" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userFormGroup.controls.disciplineMarks.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.disciplineMarks.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class LessThanCompleteComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/lessThan/complete/less-than-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-lessThan-complete-validator',
    templateUrl: './less-than-complete.component.html'
})
export class LessThanCompleteValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            obtainedMarks:['',], 
            otherActivityMarks:['', RxwebValidators.lessThan({fieldName:'obtainedMarks' })], 
            practicalExamMarks:['', RxwebValidators.lessThan({fieldName:'obtainedMarks'  ,conditionalExpression:(x,y) =>  x.obtainedMarks < 35 })], 
            passingMarks:['', RxwebValidators.lessThan({fieldName:'obtainedMarks'  ,conditionalExpression:'x => x.obtainedMarks < 35' })], 
            otherMarks:['', RxwebValidators.lessThan({fieldName:'obtainedMarks'  ,message:'Please enter number greater than 100.' })], 
            disciplineMarks:['', RxwebValidators.lessThan({fieldName:'obtainedMarks'  ,messageKey:'lessThanMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Obtained Marks</label>
      <input type="text" formControlName="obtainedMarks" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Practical Exam Marks' or 'Passing Marks', then Obtained Marks must be less than '35'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.obtainedMarks.errors">{{userFormGroup.controls.obtainedMarks.errors.lessThan.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Other Activity Marks</label>
      <input type="text" formControlName="otherActivityMarks" class="form-control"  />
      <small class="form-text text-muted">Other Activity Marks less than to Obtained marks<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.otherActivityMarks.errors">{{userFormGroup.controls.otherActivityMarks.errors.lessThan.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Practical Exam Marks</label>
      <input type="text" formControlName="practicalExamMarks" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation of less than validation on 'Practical Exam Marks' then Obtained Marks must be less than '35'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.practicalExamMarks.errors">{{userFormGroup.controls.practicalExamMarks.errors.lessThan.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Passing Marks</label>
      <input type="text" formControlName="passingMarks" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Passing Marks' then you need to add 'Obtained Marks' field less than '35'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.passingMarks.errors">{{userFormGroup.controls.passingMarks.errors.lessThan.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Other Marks</label>
      <input type="text" formControlName="otherMarks" class="form-control"  />
      <small class="form-text text-muted">Shows custom message<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.otherMarks.errors">{{userFormGroup.controls.otherMarks.errors.lessThan.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Maximum Age</label>
      <input type="text" formControlName="maximumAge" class="form-control"  />
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.maximumAge.errors">{{userFormGroup.controls.maximumAge.errors.lessThan.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Discipline Marks</label>
      <input type="text" formControlName="disciplineMarks" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.disciplineMarks.errors">{{userFormGroup.controls.disciplineMarks.errors.lessThanMessageKey.message}}<br/></small>		
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
