// Examples/vue/rxweb-reactive-forms/src/components/greaterThan/value/greater-than-value.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Minimum Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.minimumAge" type="text" name="name" />
        <div v-if="userFormGroup.controls.minimumAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.minimumAge.errors.greaterThan.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class GreaterThanValueComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/greaterThan/value/greater-than-value.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-greaterThan-value',
    templateUrl: './greater-than-value.component.html'
})
export class GreaterThanValueComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder    ) { }

    ngOnInit() {
        let user = new User();
        this.userFormGroup = this.formBuilder.formGroup(user);
    }
}
