// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/validators/file/dynamic/file-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-file-dynamic-validator',
    templateUrl: './file-dynamic.component.html'
})
export class FileDynamicValidatorComponent implements OnInit {
    userInfoFormGroup: FormGroup

				fileTypes = [ "Picture", "Document",];
	
	
	
	
	
	
	
	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/validators/file/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var userInfo = { fileType:'', totalImageFiles:'', totalDocumentFiles:'', minimumFiles:'', maximumFile:'', minMaxFiles:'', excelFiles:'',  }
			this.userInfoFormGroup = this.formBuilder.group(userInfo,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="userInfoFormGroup"  [formGroup]="userInfoFormGroup">
    <div class="form-group">
      <label>File Type</label>
      <select formControlName="fileType" class="form-control">
		<option [value]="item" *ngFor="let item of fileTypes">{{item}}</option>
      </select>
      <small class="form-text text-muted">Based on selection of file type conditional validation is applied<br/></small>
      <small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.fileType.errors">{{userInfoFormGroup.controls.fileType.errors.file.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Total Image Files</label>
      <input type="file" formControlName="totalImageFiles" class="form-control" multiple  />
      <small class="form-text text-muted">This field allow upto 5 files.<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.totalImageFiles.errors">{{userInfoFormGroup.controls.totalImageFiles.errors.file.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Total Document Files</label>
      <input type="file" formControlName="totalDocumentFiles" class="form-control" multiple  />
      <small class="form-text text-muted">This field allow minmum 5 files.<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.totalDocumentFiles.errors">{{userInfoFormGroup.controls.totalDocumentFiles.errors.file.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>MinimumFiles</label>
      <input type="file" formControlName="minimumFiles" class="form-control" multiple  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'MinimumFiles' then you need to add 'File Type' input as 'Picture'. we can add minimum 5 files<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.minimumFiles.errors">{{userInfoFormGroup.controls.minimumFiles.errors.file.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>MinMaxFiles</label>
      <input type="file" formControlName="minMaxFiles" class="form-control" multiple  />
      <small class="form-text text-muted">It shows custom message<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.minMaxFiles.errors">{{userInfoFormGroup.controls.minMaxFiles.errors.file.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Excel Files</label>
      <input type="file" formControlName="excelFiles" class="form-control" multiple  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.excelFiles.errors">{{userInfoFormGroup.controls.excelFiles.errors.file.message}}<br/></small>
    </div>
    <button [disabled]="!userInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/file/dynamic/file-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>File Type</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.fileType" type="text" name="name" />
          <small class="form-text text-muted">Based on selection of file type conditional validation is applied<br/></small>
       <div v-if="userInfoFormGroup.controls.fileType.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.fileType.errors.file.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Total Image Files</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.totalImageFiles" type="text" name="name" />
          <small class="form-text text-muted">This field allow upto 5 files.<br/></small>
       <div v-if="userInfoFormGroup.controls.totalImageFiles.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.totalImageFiles.errors.file.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Total Document Files</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.totalDocumentFiles" type="text" name="name" />
          <small class="form-text text-muted">This field allow minmum 5 files.<br/></small>
       <div v-if="userInfoFormGroup.controls.totalDocumentFiles.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.totalDocumentFiles.errors.file.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>MinimumFiles</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.minimumFiles" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'MinimumFiles' then you need to add 'File Type' input as 'Picture'. we can add minimum 5 files<br/></small>
       <div v-if="userInfoFormGroup.controls.minimumFiles.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.minimumFiles.errors.file.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Maximum File</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.maximumFile" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Maximum File' then you need to add 'File Type' input as 'Document'. we can add maximum 5 files<br/></small>
       <div v-if="userInfoFormGroup.controls.maximumFile.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.maximumFile.errors.file.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>MinMaxFiles</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.minMaxFiles" type="text" name="name" />
          <small class="form-text text-muted">It shows custom message<br/></small>
       <div v-if="userInfoFormGroup.controls.minMaxFiles.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.minMaxFiles.errors.file.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Excel Files</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.excelFiles" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userInfoFormGroup.controls.excelFiles.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.excelFiles.errors.file.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class FileDynamicComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>
