// Examples/vue/rxweb-reactive-forms/src/components/minTime/value/min-time-value.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Opening Time</label>
        <input id="name" class="form-control" v-model="attandanceDetailFormGroup.props.openingTime" type="text" name="name" />
        <div v-if="attandanceDetailFormGroup.controls.openingTime.errors">
         <small class="form-text text-danger">{{attandanceDetailFormGroup.controls.openingTime.errors.minTime.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AttandanceDetail } from './attandanceDetail.model';

@Component
export default class MinTimeValueComponent extends Vue {
 attandanceDetailFormGroup: IFormGroup<AttandanceDetail>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.attandanceDetailFormGroup = this.formBuilder.formGroup(AttandanceDetail) as IFormGroup<AttandanceDetail>;
   }
}
</script>

// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/validators/minTime/value/min-time-value.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-minTime-value-validator',
    templateUrl: './min-time-value.component.html'
})
export class MinTimeValueValidatorComponent implements OnInit {
    attandanceDetailFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.attandanceDetailFormGroup = this.formBuilder.group({
            openingTime:['', RxwebValidators.minTime({value:'08:00' })], 
        });
    }
}

<div>
  <form  [formGroup]="attandanceDetailFormGroup">
    <div class="form-group">
      <label>Opening Time</label>
      <input type="text" formControlName="openingTime" class="form-control"  />
     <small class="form-text text-danger" *ngIf="attandanceDetailFormGroup.controls.openingTime.errors">{{attandanceDetailFormGroup.controls.openingTime.errors.minTime.message}}<br/></small>	
    </div>
    <button [disabled]="!attandanceDetailFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
