// src/assets/examples/reactive-form-validators/decorators/minNumber/edit/min-number-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { ResultInfo } from './result-info.model';

@Component({
    selector: 'app-minNumber-edit',
    templateUrl: './min-number-edit.component.html'
})
export class MinNumberEditComponent implements OnInit {
    resultInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/minNumber/edit/result-info-data.json?v=' + environment.appVersion).subscribe(resultInfo => {
            this.resultInfoFormGroup = this.formBuilder.formGroup<ResultInfo>(ResultInfo,resultInfo);
        })
    }
}

<div>
  <form  *ngIf="resultInfoFormGroup"  [formGroup]="resultInfoFormGroup">
    <div class="form-group">
      <label>Maths</label>
      <input type="text" formControlName="maths" class="form-control"  />
      <small class="form-text text-muted">you can enter min number upto 35<br/></small>
	<small class="form-text text-danger" *ngIf="resultInfoFormGroup.controls.maths.errors">{{resultInfoFormGroup.controls.maths.errors.minNumber.message}}<br/></small>
    </div>
    <button [disabled]="!resultInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/minNumber/edit/min-number-edit.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Maths</label>
        <input id="name" class="form-control" v-model="resultInfoFormGroup.props.maths" type="text" name="name" />
          <small class="form-text text-muted">you can enter min number upto 35<br/></small>
       <div v-if="resultInfoFormGroup.controls.maths.errors">
         <small class="form-text text-danger">{{resultInfoFormGroup.controls.maths.errors.minNumber.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { ResultInfo } from './resultInfo.model';

@Component
export default class MinNumberEditComponent extends Vue {
 resultInfoFormGroup: IFormGroup<ResultInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.resultInfoFormGroup = this.formBuilder.formGroup(ResultInfo) as IFormGroup<ResultInfo>;
   }
}
</script>
