// Examples/vue/rxweb-reactive-forms/src/components/lessThan/value/less-than-value.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Maximum Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.maximumAge" type="text" name="name" />
        <div v-if="userFormGroup.controls.maximumAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.maximumAge.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class LessThanValueComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/template-driven/validation-directives/lessThan/value/less-than-value.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-lessThan-value-template-driven-validation-directives',
    templateUrl: './less-than-value.component.html'
})
export class LessThanValueTemplateDrivenValidationDirectivesComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>Maximum Age</label>
	    <input type="text" name="maximumAge" [(ngModel)]="user.maximumAge"  class="form-control" [lessThan]="{'value':60}"/>

	   <small class="form-text text-danger" *ngIf="userForm.controls?.maximumAge?.errors">{{userForm.controls?.maximumAge?.errors?.lessThan.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
