// src/assets/examples/reactive-form-validators/validators/different/messageKey/different-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-different-messageKey-validator',
    templateUrl: './different-message-key.component.html'
})
export class DifferentMessageKeyValidatorComponent implements OnInit {
    accountInfoFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.accountInfoFormGroup = this.formBuilder.group({
            emailAddress:['',], 
            recoveryEmailAddress:['', RxwebValidators.different({fieldName:'emailAddress'  ,messageKey:'differentMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="accountInfoFormGroup">
    <div class="form-group">
      <label>Recovery Email Address</label>
      <input type="text" formControlName="recoveryEmailAddress" class="form-control"  />
      <small class="form-text text-muted">Custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="accountInfoFormGroup.controls.recoveryEmailAddress.errors">{{accountInfoFormGroup.controls.recoveryEmailAddress.errors.different.message}}<br/></small>
    </div>
    <button [disabled]="!accountInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/different/messageKey/different-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Recovery Email Address</label>
        <input id="name" class="form-control" v-model="accountInfoFormGroup.props.recoveryEmailAddress" type="text" name="name" />
          <small class="form-text text-muted">Custom message based on message key<br/></small>
       <div v-if="accountInfoFormGroup.controls.recoveryEmailAddress.errors">
         <small class="form-text text-danger">{{accountInfoFormGroup.controls.recoveryEmailAddress.errors.different.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AccountInfo } from './accountInfo.model';

@Component
export default class DifferentMessageKeyComponent extends Vue {
 accountInfoFormGroup: IFormGroup<AccountInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.accountInfoFormGroup = this.formBuilder.formGroup(AccountInfo) as IFormGroup<AccountInfo>;
   }
}
</script>
