// Examples/vue/rxweb-reactive-forms/src/components/ascii/messageKey/ascii-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Digital Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.digitalCode" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.digitalCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.digitalCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class AsciiMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-directives/ascii/messageKey/ascii-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-ascii-messageKey-template-driven-validation-directives',
    templateUrl: './ascii-message-key.component.html'
})
export class AsciiMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>Digital Code</label>
	    <input type="text" name="digitalCode" [(ngModel)]="user.digitalCode"  class="form-control" [rxascii]="{'messageKey':'asciiMessageKey'}"/>

      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.digitalCode?.errors">{{userForm.controls?.digitalCode?.errors?.ascii.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
