// Examples/vue/rxweb-reactive-forms/src/components/minTime/operator/min-time-operator.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Required Hours</label>
        <input id="name" class="form-control" v-model="attandanceDetailFormGroup.props.requiredHours" type="text" name="name" />
          <small class="form-text text-muted">Value should be greater than 8:30<br/></small>
       <div v-if="attandanceDetailFormGroup.controls.requiredHours.errors">
         <small class="form-text text-danger">{{attandanceDetailFormGroup.controls.requiredHours.errors.minTime.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AttandanceDetail } from './attandanceDetail.model';

@Component
export default class MinTimeOperatorComponent extends Vue {
 attandanceDetailFormGroup: IFormGroup<AttandanceDetail>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.attandanceDetailFormGroup = this.formBuilder.formGroup(AttandanceDetail) as IFormGroup<AttandanceDetail>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/minTime/operator/min-time-operator.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-minTime-operator-validator',
    templateUrl: './min-time-operator.component.html'
})
export class MinTimeOperatorValidatorComponent implements OnInit {
    attandanceDetailFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.attandanceDetailFormGroup = this.formBuilder.group({
            requiredHours:['', RxwebValidators.minTime({operator:'>'  ,value:'08:30' })], 
        });
    }
}

<div>
  <form  [formGroup]="attandanceDetailFormGroup">
    <div class="form-group">
      <label>Required Hours</label>
      <input type="text" formControlName="requiredHours" class="form-control"  />
      <small class="form-text text-muted">Value should be greater than 8:30<br/></small>
     <small class="form-text text-danger" *ngIf="attandanceDetailFormGroup.controls.requiredHours.errors">{{attandanceDetailFormGroup.controls.requiredHours.errors.minTime.message}}<br/></small>	
    </div>
    <button [disabled]="!attandanceDetailFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
