// Examples/vue/rxweb-reactive-forms/src/components/notEmpty/add/not-empty-add.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>First Name</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.firstName" type="text" name="name" />
        <div v-if="userInfoFormGroup.controls.firstName.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.firstName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class NotEmptyAddComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/notEmpty/add/not-empty-add.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { UserInfo } from './user-info.model';

@Component({
    selector: 'app-notEmpty-add',
    templateUrl: './not-empty-add.component.html'
})
export class NotEmptyAddComponent implements OnInit {
    userInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder    ) { }

    ngOnInit() {
        let userInfo = new UserInfo();
        this.userInfoFormGroup = this.formBuilder.formGroup(userInfo);
    }
}

<div>
  <form  [formGroup]="userInfoFormGroup">
    <div class="form-group">
      <label>First Name</label>
      <input type="text" formControlName="firstName" class="form-control"  />
     <small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.firstName.errors">{{userInfoFormGroup.controls.firstName.errors.notEmpty.message}}<br/></small>	
    </div>
    <button [disabled]="!userInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
