// src/assets/examples/reactive-form-validators/validators/url/complete/url-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-url-complete-validator',
    templateUrl: './url-complete.component.html'
})
export class UrlCompleteValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            adminWebsiteUrl:['', RxwebValidators.url()], 
            qaWebsiteUrl:['', RxwebValidators.url({conditionalExpression:(x,y) => x.adminWebsiteUrl == "https://google.co.in"  })], 
            customerWebsiteUrl:['', RxwebValidators.url({conditionalExpression:'x => x.adminWebsiteUrl == "https://google.co.in"'  })], 
            maintenanceWebSiteUrl:['', RxwebValidators.url({message:'{{0}} Is not the correct url pattern.' })], 
            deployedWebSiteUrl:['', RxwebValidators.url({messageKey:'urlMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Admin Website Url</label>
      <input type="text" formControlName="adminWebsiteUrl" class="form-control"  />
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.adminWebsiteUrl.errors">{{userFormGroup.controls.adminWebsiteUrl.errors.url.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>QA Website Url</label>
      <input type="text" formControlName="qaWebsiteUrl" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'QA Website Url' then you need to add 'admin Website Url' input as 'https://google.co.in'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.qaWebsiteUrl.errors">{{userFormGroup.controls.qaWebsiteUrl.errors.url.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Customer Website Url</label>
      <input type="text" formControlName="customerWebsiteUrl" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Customer Website Url' then you need to add 'admin Website Url' input as 'https://google.co.in'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.customerWebsiteUrl.errors">{{userFormGroup.controls.customerWebsiteUrl.errors.url.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Maintenance Website Url</label>
      <input type="text" formControlName="maintenanceWebSiteUrl" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.maintenanceWebSiteUrl.errors">{{userFormGroup.controls.maintenanceWebSiteUrl.errors.url.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Deployed Website Url</label>
      <input type="text" formControlName="deployedWebSiteUrl" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.deployedWebSiteUrl.errors">{{userFormGroup.controls.deployedWebSiteUrl.errors.url.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/url/complete/url-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Admin Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.adminWebsiteUrl" type="text" name="name" />
        <div v-if="userFormGroup.controls.adminWebsiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.adminWebsiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>QA Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.qaWebsiteUrl" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'QA Website Url' then you need to add 'admin Website Url' input as 'https://google.co.in'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.qaWebsiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.qaWebsiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Customer Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.customerWebsiteUrl" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Customer Website Url' then you need to add 'admin Website Url' input as 'https://google.co.in'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.customerWebsiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.customerWebsiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Maintenance Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.maintenanceWebSiteUrl" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
       <div v-if="userFormGroup.controls.maintenanceWebSiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.maintenanceWebSiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Deployed Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.deployedWebSiteUrl" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message based on message key<br/></small>
       <div v-if="userFormGroup.controls.deployedWebSiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.deployedWebSiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class UrlCompleteComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
