// Examples/vue/rxweb-reactive-forms/src/components/greaterThan/message/greater-than-message.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Other Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherAge" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="userFormGroup.controls.otherAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherAge.errors.greaterThan.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class GreaterThanMessageComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/greaterThan/message/greater-than-message.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-greaterThan-message-validator',
    templateUrl: './greater-than-message.component.html'
})
export class GreaterThanMessageValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            age:['',], 
            otherAge:['', RxwebValidators.greaterThan({fieldName:'age'  ,message:'Please enter number which is greater than above field input.' })], 
        });
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Other Age</label>
      <input type="text" formControlName="otherAge" class="form-control"  />
      <small class="form-text text-muted">Shows custom message<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.otherAge.errors">{{userFormGroup.controls.otherAge.errors.greaterThan.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
