// src/assets/examples/reactive-form-validators/validators/greaterThanEqualTo/dynamic/greater-than-equal-to-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-greaterThanEqualTo-dynamic-validator',
    templateUrl: './greater-than-equal-to-dynamic.component.html'
})
export class GreaterThanEqualToDynamicValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/greaterThanEqualTo/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var user = { admissionAge:'', retiermentAge:'', voterAge:'', memberAge:'', otherAge:'', minimumAge:'', joiningAge:'',  }
			this.userFormGroup = this.formBuilder.group(user,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Admission Age</label>
      <input type="text" formControlName="admissionAge" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Voter Age' or 'Member Age' then need to add this input greater than or equal to '18'.<br/></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.admissionAge.errors">{{userFormGroup.controls.admissionAge.errors.greaterThanEqualTo.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Retirement Age</label>
      <input type="text" formControlName="retiermentAge" class="form-control"  />
      <small class="form-text text-muted">Retirement Age should be greater than equal to Admission Age<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.retiermentAge.errors">{{userFormGroup.controls.retiermentAge.errors.greaterThanEqualTo.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Member Age</label>
      <input type="text" formControlName="memberAge" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Member Age' then you need to add 'Admission Age' field greater than or equal to '18'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.memberAge.errors">{{userFormGroup.controls.memberAge.errors.greaterThanEqualTo.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Other Age</label>
      <input type="text" formControlName="otherAge" class="form-control"  />
      <small class="form-text text-muted">Shows custom message<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.otherAge.errors">{{userFormGroup.controls.otherAge.errors.greaterThanEqualTo.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Joining Age</label>
      <input type="text" formControlName="joiningAge" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.joiningAge.errors">{{userFormGroup.controls.joiningAge.errors.greaterThanEqualTo.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/greaterThanEqualTo/dynamic/greater-than-equal-to-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Admission Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.admissionAge" type="text" name="name" />
        <div v-if="userFormGroup.controls.admissionAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.admissionAge.errors.greaterThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Retirement Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.retiermentAge" type="text" name="name" />
          <small class="form-text text-muted">Retirement Age should be greater than equal to Admission Age<br/></small>
       <div v-if="userFormGroup.controls.retiermentAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.retiermentAge.errors.greaterThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Minimum Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.minimumAge" type="text" name="name" />
        <div v-if="userFormGroup.controls.minimumAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.minimumAge.errors.greaterThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Voter Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.voterAge" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Voter Age' then you need to add 'Admission Age' field greater than or equal to '18'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.voterAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.voterAge.errors.greaterThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Member Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.memberAge" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Member Age' then you need to add 'Admission Age' field greater than or equal to '18'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.memberAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.memberAge.errors.greaterThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Other Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherAge" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="userFormGroup.controls.otherAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherAge.errors.greaterThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Joining Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.joiningAge" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userFormGroup.controls.joiningAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.joiningAge.errors.greaterThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class GreaterThanEqualToDynamicComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
