// Examples/vue/rxweb-reactive-forms/src/components/greaterThanEqualTo/value/greater-than-equal-to-value.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Minimum Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.minimumAge" type="text" name="name" />
        <div v-if="userFormGroup.controls.minimumAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.minimumAge.errors.greaterThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class GreaterThanEqualToValueComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-directives/greaterThanEqualTo/value/greater-than-equal-to-value.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-greaterThanEqualTo-value-template-driven-validation-directives',
    templateUrl: './greater-than-equal-to-value.component.html'
})
export class GreaterThanEqualToValueTemplateDrivenValidationDirectivesComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>Minimum Age</label>
	    <input type="text" name="minimumAge" [(ngModel)]="user.minimumAge"  class="form-control" [greaterThanEqualTo]="{'value':18}"/>

	   <small class="form-text text-danger" *ngIf="userForm.controls?.minimumAge?.errors">{{userForm.controls?.minimumAge?.errors?.greaterThanEqualTo.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
