// src/assets/examples/reactive-form-validators/decorators/odd/edit/odd-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-odd-edit',
    templateUrl: './odd-edit.component.html'
})
export class OddEditComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/odd/edit/user-data.json?v=' + environment.appVersion).subscribe(user => {
            this.userFormGroup = this.formBuilder.formGroup<User>(User,user);
        })
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Odd Number</label>
      <input type="text" formControlName="oddNumber" class="form-control"  />
      <small class="form-text text-muted">you can enter only an odd number<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.oddNumber.errors">{{userFormGroup.controls.oddNumber.errors.odd.message}}<br/></small>	
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/odd/edit/odd-edit.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Odd Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.oddNumber" type="text" name="name" />
          <small class="form-text text-muted">you can enter only an odd number<br/></small>
       <div v-if="userFormGroup.controls.oddNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.oddNumber.errors.odd.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class OddEditComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
