// Examples/vue/rxweb-reactive-forms/src/components/date/messageKey/date-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Confirmation Date</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.confirmationDate" type="text" name="name" />
          <small class="form-text text-muted">Custom message based on messageKey<br/></small>
       <div v-if="userInfoFormGroup.controls.confirmationDate.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.confirmationDate.errors.date.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class DateMessageKeyComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-decorators/date/messageKey/date-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { UserInfo } from './user-info.model';

@Component({
    selector: 'app-date-messageKey-template-driven-validation-decorators',
    templateUrl: './date-message-key.component.html'
})
export class DateMessageKeyTemplateDrivenValidationDecoratorsComponent implements OnInit {
    userinfo: UserInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.userinfo= new UserInfo()
    }
}

<div>
  <form #userinfoForm = "ngForm" [rxwebForm]="userinfoForm" [model]="userinfo">
    <div class="form-group">
      <label>Confirmation Date</label>
	    <input type="text" name="confirmationDate" [(ngModel)]="userinfo.confirmationDate"  class="form-control" />

      <small class="form-text text-muted">Custom message based on messageKey<br/></small>
	   <small class="form-text text-danger" *ngIf="userinfoForm.controls?.confirmationDate?.errors">{{userinfoForm.controls?.confirmationDate?.errors?.date.message}}<br/></small>	
    </div>
    <button [disabled]="!userinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
