// Examples/vue/rxweb-reactive-forms/src/components/extension/messageKey/extension-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Excel File</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.excelFile" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userInfoFormGroup.controls.excelFile.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.excelFile.errors.extension.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class ExtensionMessageKeyComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/extension/messageKey/extension-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { UserInfo } from './user-info.model';

@Component({
    selector: 'app-extension-messageKey',
    templateUrl: './extension-message-key.component.html'
})
export class ExtensionMessageKeyComponent implements OnInit {
    userInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder    ) { }

    ngOnInit() {
        let userInfo = new UserInfo();
        this.userInfoFormGroup = this.formBuilder.formGroup(userInfo);
    }
}

<div>
  <form  [formGroup]="userInfoFormGroup">
    <div class="form-group">
      <label>Excel File</label>
      <input type="file" formControlName="excelFile" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
     <small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.excelFile.errors">{{userInfoFormGroup.controls.excelFile.errors.extensionMessageKey.message}}<br/></small>		
    </div>
    <button [disabled]="!userInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
