// Examples/vue/rxweb-reactive-forms/src/components/numeric/complete/numeric-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Data Type</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.dataType" type="text" name="name" />
        <div v-if="userInfoFormGroup.controls.dataType.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.dataType.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Negative Number</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.negativeNumber" type="text" name="name" />
          <small class="form-text text-muted">you can enter only a negative number<br/></small>
       <div v-if="userInfoFormGroup.controls.negativeNumber.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.negativeNumber.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Total Amount</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.totalAmount" type="text" name="name" />
        <div v-if="userInfoFormGroup.controls.totalAmount.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.totalAmount.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Decimal Number</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.decimalNumber" type="text" name="name" />
          <small class="form-text text-muted">you can enter only a positive decimal number<br/></small>
       <div v-if="userInfoFormGroup.controls.decimalNumber.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.decimalNumber.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Integer Number</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.integerNumber" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Integer Number' then you need to add 'Data Type' input as 'Integer'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userInfoFormGroup.controls.integerNumber.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.integerNumber.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Real Number</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.realNumber" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Real Number' then you need to add 'Data Type' input as 'Real'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userInfoFormGroup.controls.realNumber.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.realNumber.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Positive Number</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.positiveNumber" type="text" name="name" />
          <small class="form-text text-muted">you can enter only a positive number<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userInfoFormGroup.controls.positiveNumber.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.positiveNumber.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Positive Non Decimal Number</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.positiveNonDecimalNumber" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userInfoFormGroup.controls.positiveNonDecimalNumber.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.positiveNonDecimalNumber.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class NumericCompleteComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/numeric/complete/numeric-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators ,NumericValueType} from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-numeric-complete-validator',
    templateUrl: './numeric-complete.component.html'
})
export class NumericCompleteValidatorComponent implements OnInit {
    userInfoFormGroup: FormGroup

				dataTypes = [ "Real", "Integer",];
	
	
	
	
	
	
	
	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userInfoFormGroup = this.formBuilder.group({
            dataType:['',], 
            negativeNumber:['', RxwebValidators.numeric({acceptValue:NumericValueType.NegativeNumber })], 
            decimalNumber:['', RxwebValidators.numeric({allowDecimal:true })], 
            integerNumber:['', RxwebValidators.numeric({acceptValue:NumericValueType.PositiveNumber  ,conditionalExpression:(x,y) => x.dataType == "Integer"  })], 
            realNumber:['', RxwebValidators.numeric({acceptValue:NumericValueType.Both  ,conditionalExpression:'x => x.dataType == "Real"' })], 
            positiveNumber:['', RxwebValidators.numeric({message:'{{0}} is not a positive number' })], 
            positiveNonDecimalNumber:['', RxwebValidators.numeric({messageKey:'numericMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userInfoFormGroup">
    <div class="form-group">
      <label>Data Type</label>
      <select formControlName="dataType" class="form-control">
		<option [value]="item" *ngFor="let item of dataTypes">{{item}}</option>
      </select>
     <small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.dataType.errors">{{userInfoFormGroup.controls.dataType.errors.numeric.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Negative Number</label>
      <input type="text" formControlName="negativeNumber" class="form-control"  />
      <small class="form-text text-muted">you can enter only a negative number<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.negativeNumber.errors">{{userInfoFormGroup.controls.negativeNumber.errors.numeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Total Amount</label>
      <input type="text" formControlName="totalAmount" class="form-control"  />
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.totalAmount.errors">{{userInfoFormGroup.controls.totalAmount.errors.numeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Decimal Number</label>
      <input type="text" formControlName="decimalNumber" class="form-control"  />
      <small class="form-text text-muted">you can enter only a positive decimal number<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.decimalNumber.errors">{{userInfoFormGroup.controls.decimalNumber.errors.numeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Integer Number</label>
      <input type="text" formControlName="integerNumber" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Integer Number' then you need to add 'Data Type' input as 'Integer'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.integerNumber.errors">{{userInfoFormGroup.controls.integerNumber.errors.numeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Real Number</label>
      <input type="text" formControlName="realNumber" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Real Number' then you need to add 'Data Type' input as 'Real'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.realNumber.errors">{{userInfoFormGroup.controls.realNumber.errors.numeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Positive Number</label>
      <input type="text" formControlName="positiveNumber" class="form-control"  />
      <small class="form-text text-muted">you can enter only a positive number<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.positiveNumber.errors">{{userInfoFormGroup.controls.positiveNumber.errors.numeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Positive Non Decimal Number</label>
      <input type="text" formControlName="positiveNonDecimalNumber" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.positiveNonDecimalNumber.errors">{{userInfoFormGroup.controls.positiveNonDecimalNumber.errors.numeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Formatted Decimal Number</label>
      <input type="text" formControlName="formattedDecimalNumber" class="form-control"  />
      <small class="form-text text-muted">Format the decimal input upto 2 decimal places<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.formattedDecimalNumber.errors">{{userInfoFormGroup.controls.formattedDecimalNumber.errors.numeric.message}}<br/></small>
    </div>
    <button [disabled]="!userInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
