// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/template-driven/validation-directives/required/messageKey/required-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-required-messageKey-template-driven-validation-directives',
    templateUrl: './required-message-key.component.html'
})
export class RequiredMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>Full Name</label>
	    <input type="text" name="fullName" [(ngModel)]="user.fullName"  class="form-control" [required]="{'messageKey':'requiredMessageKey'}"/>

      <small class="form-text text-muted">Shows Custom Validation Message based on message key<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.fullName?.errors">{{userForm.controls?.fullName?.errors?.required.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/required/messageKey/required-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Full Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.fullName" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message based on message key<br/></small>
       <div v-if="userFormGroup.controls.fullName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.fullName.errors.required.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class RequiredMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
