// Examples/vue/rxweb-reactive-forms/src/components/alpha/messageKey/alpha-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>City Code</label>
        <input id="name" class="form-control" v-model="addressInfoFormGroup.props.cityCode" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="addressInfoFormGroup.controls.cityCode.errors">
         <small class="form-text text-danger">{{addressInfoFormGroup.controls.cityCode.errors.alpha.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AddressInfo } from './addressInfo.model';

@Component
export default class AlphaMessageKeyComponent extends Vue {
 addressInfoFormGroup: IFormGroup<AddressInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.addressInfoFormGroup = this.formBuilder.formGroup(AddressInfo) as IFormGroup<AddressInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/alpha/messageKey/alpha-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { AddressInfo } from './address-info.model';

@Component({
    selector: 'app-alpha-messageKey',
    templateUrl: './alpha-message-key.component.html'
})
export class AlphaMessageKeyComponent implements OnInit {
    addressInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder    ) { }

    ngOnInit() {
        let addressInfo = new AddressInfo();
        this.addressInfoFormGroup = this.formBuilder.formGroup(addressInfo);
    }
}

<div>
  <form  [formGroup]="addressInfoFormGroup">
    <div class="form-group">
      <label>City Code</label>
      <input type="text" formControlName="cityCode" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="addressInfoFormGroup.controls.cityCode.errors">{{addressInfoFormGroup.controls.cityCode.errors.alpha.message}}<br/></small>
    </div>
    <button [disabled]="!addressInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
