// Examples/vue/rxweb-reactive-forms/src/components/latLong/messageKey/lat-long-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Fourth Country</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.fourthCountry" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
       <div v-if="countryFormGroup.controls.fourthCountry.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.fourthCountry.errors.latLong.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Country } from './country.model';

@Component
export default class LatLongMessageKeyComponent extends Vue {
 countryFormGroup: IFormGroup<Country>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.countryFormGroup = this.formBuilder.formGroup(Country) as IFormGroup<Country>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-decorators/latLong/messageKey/lat-long-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { Country } from './country.model';

@Component({
    selector: 'app-latLong-messageKey-template-driven-validation-decorators',
    templateUrl: './lat-long-message-key.component.html'
})
export class LatLongMessageKeyTemplateDrivenValidationDecoratorsComponent implements OnInit {
    country: Country
	
    constructor(
    ) { }

    ngOnInit() {
       this.country= new Country()
    }
}

<div>
  <form #countryForm = "ngForm" [rxwebForm]="countryForm" [model]="country">
    <div class="form-group">
      <label>Fourth Country</label>
	    <input type="text" name="fourthCountry" [(ngModel)]="country.fourthCountry"  class="form-control" />

      <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
	   <small class="form-text text-danger" *ngIf="countryForm.controls?.fourthCountry?.errors">{{countryForm.controls?.fourthCountry?.errors?.latLong.message}}<br/></small>	
    </div>
    <button [disabled]="!countryForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
