// Examples/vue/rxweb-reactive-forms/src/components/minNumber/dynamic/min-number-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Maths</label>
        <input id="name" class="form-control" v-model="resultInfoFormGroup.props.maths" type="text" name="name" />
        <div v-if="resultInfoFormGroup.controls.maths.errors">
         <small class="form-text text-danger">{{resultInfoFormGroup.controls.maths.errors.minNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Science</label>
        <input id="name" class="form-control" v-model="resultInfoFormGroup.props.science" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message<br/></small>
         <small class="form-text text-muted">you can enter min number upto 35<br/></small>
       <div v-if="resultInfoFormGroup.controls.science.errors">
         <small class="form-text text-danger">{{resultInfoFormGroup.controls.science.errors.minNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>English</label>
        <input id="name" class="form-control" v-model="resultInfoFormGroup.props.english" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'English' then you need to add 'Maths' input as '50'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="resultInfoFormGroup.controls.english.errors">
         <small class="form-text text-danger">{{resultInfoFormGroup.controls.english.errors.minNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Statstics</label>
        <input id="name" class="form-control" v-model="resultInfoFormGroup.props.statstics" type="text" name="name" />
          <small class="form-text text-muted">Conditional validation will be applied if the 'Statstics' field have value of '50'<br/></small>
         <small class="form-text text-muted">you can enter min number upto 35<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="resultInfoFormGroup.controls.statstics.errors">
         <small class="form-text text-danger">{{resultInfoFormGroup.controls.statstics.errors.minNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Economics</label>
        <input id="name" class="form-control" v-model="resultInfoFormGroup.props.economics" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message using message key<br/></small>
       <div v-if="resultInfoFormGroup.controls.economics.errors">
         <small class="form-text text-danger">{{resultInfoFormGroup.controls.economics.errors.minNumber.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { ResultInfo } from './resultInfo.model';

@Component
export default class MinNumberDynamicComponent extends Vue {
 resultInfoFormGroup: IFormGroup<ResultInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.resultInfoFormGroup = this.formBuilder.formGroup(ResultInfo) as IFormGroup<ResultInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/minNumber/dynamic/min-number-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';
import { FormBuilderConfiguration,} from '@rxweb/reactive-form-validators';

import { ResultInfo } from './result-info.model';

@Component({
    selector: 'app-minNumber-dynamic',
    templateUrl: './min-number-dynamic.component.html'
})
export class MinNumberDynamicComponent implements OnInit {
    resultInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        let resultInfo = new ResultInfo();
        let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/minNumber/dynamic/dynamic.json?v=' + environment.appVersion).subscribe(dynamic => {
            formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			this.resultInfoFormGroup = this.formBuilder.formGroup(resultInfo,formBuilderConfiguration);
        })
    }
}

<div>
  <form  *ngIf="resultInfoFormGroup"  [formGroup]="resultInfoFormGroup">
    <div class="form-group">
      <label>Maths</label>
      <input type="text" formControlName="maths" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'English' or 'Statstics', then you need to add 'Maths' input as '50'<br/></small>
	<small class="form-text text-danger" *ngIf="resultInfoFormGroup.controls.maths.errors">{{resultInfoFormGroup.controls.maths.errors.minNumber.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Science</label>
      <input type="text" formControlName="science" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message<br/></small>
      <small class="form-text text-muted">you can enter min number upto 35<br/></small>
	<small class="form-text text-danger" *ngIf="resultInfoFormGroup.controls.science.errors">{{resultInfoFormGroup.controls.science.errors.minNumber.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Statstics</label>
      <input type="text" formControlName="statstics" class="form-control"  />
      <small class="form-text text-muted">Conditional validation will be applied if the 'Maths' field have value of '50'<br/></small>
      <small class="form-text text-muted">you can enter min number upto 35<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="resultInfoFormGroup.controls.statstics.errors">{{resultInfoFormGroup.controls.statstics.errors.minNumber.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Economics</label>
      <input type="text" formControlName="economics" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message using message key<br/></small>
	<small class="form-text text-danger" *ngIf="resultInfoFormGroup.controls.economics.errors">{{resultInfoFormGroup.controls.economics.errors.minNumber.message}}<br/></small>
    </div>
    <button [disabled]="!resultInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
