// src/assets/examples/reactive-form-validators/validators/json/dynamic/json-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-json-dynamic-validator',
    templateUrl: './json-dynamic.component.html'
})
export class JsonDynamicValidatorComponent implements OnInit {
    jsonInfoFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/json/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var jsonInfo = { location:'', addressJson:'', locationJson:'', contactJson:'', countryJson:'',  }
			this.jsonInfoFormGroup = this.formBuilder.group(jsonInfo,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="jsonInfoFormGroup"  [formGroup]="jsonInfoFormGroup">
    <div class="form-group">
      <label>Location</label>
      <input type="text" formControlName="location" class="form-control"  />
      <small class="form-text text-muted">'To apply the validation of JSON on 'addressJson' or 'locationJson' field, then enter the value of location is &#123;CountryName:India&#125; in Location textbox.<br/></small>
	<small class="form-text text-danger" *ngIf="jsonInfoFormGroup.controls.location.errors">{{jsonInfoFormGroup.controls.location.errors.json.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Location Json</label>
      <input type="text" formControlName="locationJson" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Location Json' then you need to add 'Location' input as &#123;CountryName:India&#125;.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="jsonInfoFormGroup.controls.locationJson.errors">{{jsonInfoFormGroup.controls.locationJson.errors.json.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Contact Json</label>
      <input type="text" formControlName="contactJson" class="form-control"  />
      <small class="form-text text-muted">Shows custom message<br/></small>
	<small class="form-text text-danger" *ngIf="jsonInfoFormGroup.controls.contactJson.errors">{{jsonInfoFormGroup.controls.contactJson.errors.json.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Country Json</label>
      <input type="text" formControlName="countryJson" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on Message Key<br/></small>
	<small class="form-text text-danger" *ngIf="jsonInfoFormGroup.controls.countryJson.errors">{{jsonInfoFormGroup.controls.countryJson.errors.json.message}}<br/></small>
    </div>
    <button [disabled]="!jsonInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/json/dynamic/json-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Location</label>
        <input id="name" class="form-control" v-model="jsonInfoFormGroup.props.location" type="text" name="name" />
        <div v-if="jsonInfoFormGroup.controls.location.errors">
         <small class="form-text text-danger">{{jsonInfoFormGroup.controls.location.errors.json.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Address Json</label>
        <input id="name" class="form-control" v-model="jsonInfoFormGroup.props.addressJson" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Address Json' then you need to add 'Location' input as &#123;CountryName:India&#125;.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="jsonInfoFormGroup.controls.addressJson.errors">
         <small class="form-text text-danger">{{jsonInfoFormGroup.controls.addressJson.errors.json.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Location Json</label>
        <input id="name" class="form-control" v-model="jsonInfoFormGroup.props.locationJson" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Location Json' then you need to add 'Location' input as &#123;CountryName:India&#125;.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="jsonInfoFormGroup.controls.locationJson.errors">
         <small class="form-text text-danger">{{jsonInfoFormGroup.controls.locationJson.errors.json.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Contact Json</label>
        <input id="name" class="form-control" v-model="jsonInfoFormGroup.props.contactJson" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="jsonInfoFormGroup.controls.contactJson.errors">
         <small class="form-text text-danger">{{jsonInfoFormGroup.controls.contactJson.errors.json.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Country Json</label>
        <input id="name" class="form-control" v-model="jsonInfoFormGroup.props.countryJson" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on Message Key<br/></small>
       <div v-if="jsonInfoFormGroup.controls.countryJson.errors">
         <small class="form-text text-danger">{{jsonInfoFormGroup.controls.countryJson.errors.json.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { JsonInfo } from './jsonInfo.model';

@Component
export default class JsonDynamicComponent extends Vue {
 jsonInfoFormGroup: IFormGroup<JsonInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.jsonInfoFormGroup = this.formBuilder.formGroup(JsonInfo) as IFormGroup<JsonInfo>;
   }
}
</script>
