// Examples/vue/rxweb-reactive-forms/src/components/creditCard/edit/credit-card-edit.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Card Type</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.cardType" type="text" name="name" />
          <small class="form-text text-muted">Based on selection of card type conditional validation is applied<br/></small>
       <div v-if="userFormGroup.controls.cardType.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.cardType.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Credit Card No.</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.creditCardNumber" type="text" name="name" />
          <small class="form-text text-muted">Enter Visa Card No<br/></small>
       <div v-if="userFormGroup.controls.creditCardNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.creditCardNumber.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class CreditCardEditComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/decorators/creditCard/edit/credit-card-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-creditCard-edit',
    templateUrl: './credit-card-edit.component.html'
})
export class CreditCardEditComponent implements OnInit {
    userFormGroup: FormGroup
				creditCardTypes = [ "Visa", "AmericanExpress", "Maestro", "JCB", "Discover", "DinersClub", "MasterCard",];

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/creditCard/edit/user-data.json?v=' + environment.appVersion).subscribe(user => {
            this.userFormGroup = this.formBuilder.formGroup<User>(User,user);
        })
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Card Type</label>
      <select formControlName="cardType" class="form-control">
		<option [value]="item" *ngFor="let item of creditCardTypes">{{item}}</option>
      </select>
      <small class="form-text text-muted">Based on selection of card type conditional validation is applied<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.cardType.errors">{{userFormGroup.controls.cardType.errors.creditCard.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Credit Card No.</label>
      <input type="text" formControlName="creditCardNumber" class="form-control"  />
      <small class="form-text text-muted">Enter Visa Card No<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.creditCardNumber.errors">{{userFormGroup.controls.creditCardNumber.errors.creditCard.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
