// src/assets/examples/reactive-form-validators/template-driven/validation-decorators/minNumber/messageKey/min-number-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { ResultInfo } from './result-info.model';

@Component({
    selector: 'app-minNumber-messageKey-template-driven-validation-decorators',
    templateUrl: './min-number-message-key.component.html'
})
export class MinNumberMessageKeyTemplateDrivenValidationDecoratorsComponent implements OnInit {
    resultinfo: ResultInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.resultinfo= new ResultInfo()
    }
}

<div>
  <form #resultinfoForm = "ngForm" [rxwebForm]="resultinfoForm" [model]="resultinfo">
    <div class="form-group">
      <label>Economics</label>
	    <input type="text" name="economics" [(ngModel)]="resultinfo.economics"  class="form-control" />

      <small class="form-text text-muted">Shows Custom Validation Message using message key<br/></small>
	   <small class="form-text text-danger" *ngIf="resultinfoForm.controls?.economics?.errors">{{resultinfoForm.controls?.economics?.errors?.minNumber.message}}<br/></small>	
    </div>
    <button [disabled]="!resultinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/minNumber/messageKey/min-number-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Economics</label>
        <input id="name" class="form-control" v-model="resultInfoFormGroup.props.economics" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message using message key<br/></small>
       <div v-if="resultInfoFormGroup.controls.economics.errors">
         <small class="form-text text-danger">{{resultInfoFormGroup.controls.economics.errors.minNumber.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { ResultInfo } from './resultInfo.model';

@Component
export default class MinNumberMessageKeyComponent extends Vue {
 resultInfoFormGroup: IFormGroup<ResultInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.resultInfoFormGroup = this.formBuilder.formGroup(ResultInfo) as IFormGroup<ResultInfo>;
   }
}
</script>
