// Examples/vue/rxweb-reactive-forms/src/components/leapYear/dynamic/leap-year-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.name" type="text" name="name" />
        <div v-if="userFormGroup.controls.name.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.name.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Birth Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.birthYear" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of leapYear on 'Birth Year' field, then enter 'Bharat' in 'Name' textbox<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.birthYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.birthYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Admission Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.admissionYear" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of leapYear on 'Admission Year' field, then enter 'Bharat' in 'Name' textbox<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.admissionYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.admissionYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Joining Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.joiningYear" type="text" name="name" />
          <small class="form-text text-muted">you can enter only a leap year<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.joiningYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.joiningYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Promotion Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.promotionYear" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
       <div v-if="userFormGroup.controls.promotionYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.promotionYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class LeapYearDynamicComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/leapYear/dynamic/leap-year-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';
import { FormBuilderConfiguration,} from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-leapYear-dynamic',
    templateUrl: './leap-year-dynamic.component.html'
})
export class LeapYearDynamicComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        let user = new User();
        let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/leapYear/dynamic/dynamic.json?v=' + environment.appVersion).subscribe(dynamic => {
            formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			this.userFormGroup = this.formBuilder.formGroup(user,formBuilderConfiguration);
        })
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Name</label>
      <input type="text" formControlName="name" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Birth Year' or 'Admission Date', then you need to add 'Name' input as 'Bharat'<br/></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.name.errors">{{userFormGroup.controls.name.errors.leapYear.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Admission Year</label>
      <input type="text" formControlName="admissionYear" class="form-control"  />
      <small class="form-text text-muted">To apply the validation of leap on 'Admission Year' field, then enter the value 'Bharat' in 'Name' textbox<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.admissionYear.errors">{{userFormGroup.controls.admissionYear.errors.leapYear.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Joining Year</label>
      <input type="text" formControlName="joiningYear" class="form-control"  />
      <small class="form-text text-muted">you can enter only a leap year<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.joiningYear.errors">{{userFormGroup.controls.joiningYear.errors.leapYear.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Promotion Year</label>
      <input type="text" formControlName="promotionYear" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.promotionYear.errors">{{userFormGroup.controls.promotionYear.errors.leapYear.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
