// Examples/vue/rxweb-reactive-forms/src/components/notEmpty/add/not-empty-add.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>First Name</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.firstName" type="text" name="name" />
        <div v-if="userInfoFormGroup.controls.firstName.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.firstName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class NotEmptyAddComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-directives/notEmpty/add/not-empty-add.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { UserInfo } from './user-info.model';

@Component({
    selector: 'app-notEmpty-add-template-driven-validation-directives',
    templateUrl: './not-empty-add.component.html'
})
export class NotEmptyAddTemplateDrivenValidationDirectivesComponent implements OnInit {
    userinfo: UserInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.userinfo= new UserInfo()
    }
}

<div>
  <form #userinfoForm = "ngForm" [rxwebForm]="userinfoForm" [model]="userinfo">
    <div class="form-group">
      <label>First Name</label>
	    <input type="text" name="firstName" [(ngModel)]="userinfo.firstName"  class="form-control" rxnotEmpty/>

	   <small class="form-text text-danger" *ngIf="userinfoForm.controls?.firstName?.errors">{{userinfoForm.controls?.firstName?.errors?.notEmpty.message}}<br/></small>	
    </div>
    <button [disabled]="!userinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
