// Examples/vue/rxweb-reactive-forms/src/components/minDate/messageKey/min-date-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Resignation Date</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.resignationDate" type="text" name="name" />
          <small class="form-text text-muted">Enterred date must be greater than the 30th July 2018<br/></small>
         <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userFormGroup.controls.resignationDate.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.resignationDate.errors.minDate.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class MinDateMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-directives/minDate/messageKey/min-date-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-minDate-messageKey-template-driven-validation-directives',
    templateUrl: './min-date-message-key.component.html'
})
export class MinDateMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>Resignation Date</label>
	    <input type="text" name="resignationDate" [(ngModel)]="user.resignationDate"  class="form-control" [rxminDate]="{'value':'07/30/2018','messageKey':'minDateMessageKey'}"/>

      <small class="form-text text-muted">Enterred date must be greater than the 30th July 2018<br/></small>
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.resignationDate?.errors">{{userForm.controls?.resignationDate?.errors?.minDate.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
