// src/assets/examples/reactive-form-validators/decorators/cusip/edit/cusip-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { CompanyInfo } from './company-info.model';

@Component({
    selector: 'app-cusip-edit',
    templateUrl: './cusip-edit.component.html'
})
export class CusipEditComponent implements OnInit {
    companyInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/cusip/edit/company-info-data.json?v=' + environment.appVersion).subscribe(companyInfo => {
            this.companyInfoFormGroup = this.formBuilder.formGroup<CompanyInfo>(CompanyInfo,companyInfo);
        })
    }
}

<div>
  <form  *ngIf="companyInfoFormGroup"  [formGroup]="companyInfoFormGroup">
    <div class="form-group">
      <label>Oracle Corporation Cusip Code</label>
      <input type="text" formControlName="oracleCorporationCusipCode" class="form-control"  />
      <small class="form-text text-muted">You must enter a valid cusip Code only<br/></small>
     <small class="form-text text-danger" *ngIf="companyInfoFormGroup.controls.oracleCorporationCusipCode.errors">{{companyInfoFormGroup.controls.oracleCorporationCusipCode.errors.cusip.message}}<br/></small>	
    </div>
    <button [disabled]="!companyInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/cusip/edit/cusip-edit.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Oracle Corporation Cusip Code</label>
        <input id="name" class="form-control" v-model="companyInfoFormGroup.props.oracleCorporationCusipCode" type="text" name="name" />
          <small class="form-text text-muted">You must enter a valid cusip Code only<br/></small>
       <div v-if="companyInfoFormGroup.controls.oracleCorporationCusipCode.errors">
         <small class="form-text text-danger">{{companyInfoFormGroup.controls.oracleCorporationCusipCode.errors.cusip.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { CompanyInfo } from './companyInfo.model';

@Component
export default class CusipEditComponent extends Vue {
 companyInfoFormGroup: IFormGroup<CompanyInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.companyInfoFormGroup = this.formBuilder.formGroup(CompanyInfo) as IFormGroup<CompanyInfo>;
   }
}
</script>
