// src/assets/examples/reactive-form-validators/validators/alphaNumeric/dynamic/alpha-numeric-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-alphaNumeric-dynamic-validator',
    templateUrl: './alpha-numeric-dynamic.component.html'
})
export class AlphaNumericDynamicValidatorComponent implements OnInit {
    locationFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/alphaNumeric/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var location = { areaName:'', flatAddress:'', postalAddress:'', countryCode:'', cityCode:'', colonyName:'',  }
			this.locationFormGroup = this.formBuilder.group(location,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="locationFormGroup"  [formGroup]="locationFormGroup">
    <div class="form-group">
      <label>Area Name</label>
      <input type="text" formControlName="areaName" class="form-control"   />
      <small class="form-text text-danger" *ngIf="locationFormGroup.controls.areaName.errors">{{locationFormGroup.controls.areaName.errors.alphaNumeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Flat Address</label>
      <input type="text" formControlName="flatAddress" class="form-control"  />
      <small class="form-text text-muted">This allowed whitespace in alpha Numeric validation<br/></small>
     <small class="form-text text-danger" *ngIf="locationFormGroup.controls.flatAddress.errors">{{locationFormGroup.controls.flatAddress.errors.alphaNumeric.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>SpanishCityName</label>
      <input type="text" formControlName="spanishcityName" class="form-control"  />
      <small class="form-text text-muted">It will allow spanish characters in the formControl<br/></small>
     <small class="form-text text-danger" *ngIf="locationFormGroup.controls.spanishcityName.errors">{{locationFormGroup.controls.spanishcityName.errors.alphaNumeric.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Postal Address</label>
      <input type="text" formControlName="postalAddress" class="form-control"  />
      <small class="form-text text-muted">Shows custom message<br/></small>
     <small class="form-text text-danger" *ngIf="locationFormGroup.controls.postalAddress.errors">{{locationFormGroup.controls.postalAddress.errors.alphaNumeric.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>City Code</label>
      <input type="text" formControlName="cityCode" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on this field then you need to add 'areaName' input as 'Delhi'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
     <small class="form-text text-danger" *ngIf="locationFormGroup.controls.cityCode.errors">{{locationFormGroup.controls.cityCode.errors.alphaNumeric.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Colony Name</label>
      <input type="text" formControlName="colonyName" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
     <small class="form-text text-danger" *ngIf="locationFormGroup.controls.colonyName.errors">{{locationFormGroup.controls.colonyName.errors.alphaNumericMessageKey.message}}<br/></small>		
    </div>
    <button [disabled]="!locationFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/alphaNumeric/dynamic/alpha-numeric-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Area Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.areaName" type="text" name="name" />
        <div v-if="locationFormGroup.controls.areaName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.areaName.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Flat Address</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.flatAddress" type="text" name="name" />
          <small class="form-text text-muted">This allowed whitespace in alpha Numeric validation<br/></small>
       <div v-if="locationFormGroup.controls.flatAddress.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.flatAddress.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Postal Address</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.postalAddress" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="locationFormGroup.controls.postalAddress.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.postalAddress.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Country Code</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.countryCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on this field then you need to add 'areaName' input as 'Delhi'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="locationFormGroup.controls.countryCode.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.countryCode.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>City Code</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.cityCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on this field then you need to add 'areaName' input as 'Delhi'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="locationFormGroup.controls.cityCode.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.cityCode.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Colony Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.colonyName" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="locationFormGroup.controls.colonyName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.colonyName.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Location } from './location.model';

@Component
export default class AlphaNumericDynamicComponent extends Vue {
 locationFormGroup: IFormGroup<Location>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.locationFormGroup = this.formBuilder.formGroup(Location) as IFormGroup<Location>;
   }
}
</script>
