// Examples/vue/rxweb-reactive-forms/src/components/extension/messageKey/extension-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Excel File</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.excelFile" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userInfoFormGroup.controls.excelFile.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.excelFile.errors.extension.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class ExtensionMessageKeyComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-directives/extension/messageKey/extension-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { UserInfo } from './user-info.model';

@Component({
    selector: 'app-extension-messageKey-template-driven-validation-directives',
    templateUrl: './extension-message-key.component.html'
})
export class ExtensionMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    userinfo: UserInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.userinfo= new UserInfo()
    }
}

<div>
  <form #userinfoForm = "ngForm" [rxwebForm]="userinfoForm" [model]="userinfo">
    <div class="form-group">
      <label>Excel File</label>
	    <input type="file" name="excelFile"  [(ngModel)]="userinfo.excelFile"  class="form-control" [rxextension]="{'extensions':['xls','xlsx'],'messageKey':'extensionMessageKey'}"/>

      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	   <small class="form-text text-danger" *ngIf="userinfoForm.controls?.excelFile?.errors">{{userinfoForm.controls?.excelFile?.errors?.extension.message}}<br/></small>	
    </div>
    <button [disabled]="!userinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
