// src/assets/examples/reactive-form-validators/validators/mac/dynamic/mac-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-mac-dynamic-validator',
    templateUrl: './mac-dynamic.component.html'
})
export class MacDynamicValidatorComponent implements OnInit {
    macAddressInfoFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/validators/mac/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var macAddressInfo = { device:'', macAddress:'', localMacAddress:'', systemMacAddress:'', serverMacAddress:'',  }
			this.macAddressInfoFormGroup = this.formBuilder.group(macAddressInfo,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="macAddressInfoFormGroup"  [formGroup]="macAddressInfoFormGroup">
    <div class="form-group">
      <label>Device</label>
      <input type="text" formControlName="device" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'MAC Address' or 'Local MAC Address', then you need to add 'Device' input as 'Laptop'<br/></small>
      <small class="form-text text-danger" *ngIf="macAddressInfoFormGroup.controls.device.errors">{{macAddressInfoFormGroup.controls.device.errors.mac.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Local MAC Address</label>
      <input type="text" formControlName="localMacAddress" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Local MAC Address' then you need to add 'Device' input as 'Laptop'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="macAddressInfoFormGroup.controls.localMacAddress.errors">{{macAddressInfoFormGroup.controls.localMacAddress.errors.mac.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>System MAC Address</label>
      <input type="text" formControlName="systemMacAddress" class="form-control"  />
      <small class="form-text text-muted">enter MAC address only<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="macAddressInfoFormGroup.controls.systemMacAddress.errors">{{macAddressInfoFormGroup.controls.systemMacAddress.errors.mac.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Server MAC Address</label>
      <input type="text" formControlName="serverMacAddress" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="macAddressInfoFormGroup.controls.serverMacAddress.errors">{{macAddressInfoFormGroup.controls.serverMacAddress.errors.mac.message}}<br/></small>
    </div>
    <button [disabled]="!macAddressInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/mac/dynamic/mac-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Device</label>
        <input id="name" class="form-control" v-model="macAddressInfoFormGroup.props.device" type="text" name="name" />
        <div v-if="macAddressInfoFormGroup.controls.device.errors">
         <small class="form-text text-danger">{{macAddressInfoFormGroup.controls.device.errors.mac.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>MAC Address</label>
        <input id="name" class="form-control" v-model="macAddressInfoFormGroup.props.macAddress" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'MAC Address' then you need to add 'Device' input as 'Laptop'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="macAddressInfoFormGroup.controls.macAddress.errors">
         <small class="form-text text-danger">{{macAddressInfoFormGroup.controls.macAddress.errors.mac.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Local MAC Address</label>
        <input id="name" class="form-control" v-model="macAddressInfoFormGroup.props.localMacAddress" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Local MAC Address' then you need to add 'Device' input as 'Laptop'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="macAddressInfoFormGroup.controls.localMacAddress.errors">
         <small class="form-text text-danger">{{macAddressInfoFormGroup.controls.localMacAddress.errors.mac.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>System MAC Address</label>
        <input id="name" class="form-control" v-model="macAddressInfoFormGroup.props.systemMacAddress" type="text" name="name" />
          <small class="form-text text-muted">enter MAC address only<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="macAddressInfoFormGroup.controls.systemMacAddress.errors">
         <small class="form-text text-danger">{{macAddressInfoFormGroup.controls.systemMacAddress.errors.mac.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Server MAC Address</label>
        <input id="name" class="form-control" v-model="macAddressInfoFormGroup.props.serverMacAddress" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="macAddressInfoFormGroup.controls.serverMacAddress.errors">
         <small class="form-text text-danger">{{macAddressInfoFormGroup.controls.serverMacAddress.errors.mac.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { MacAddressInfo } from './macAddressInfo.model';

@Component
export default class MacDynamicComponent extends Vue {
 macAddressInfoFormGroup: IFormGroup<MacAddressInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.macAddressInfoFormGroup = this.formBuilder.formGroup(MacAddressInfo) as IFormGroup<MacAddressInfo>;
   }
}
</script>
