// src/assets/examples/reactive-form-validators/template-driven/validation-decorators/minTime/allowSeconds/min-time-allow-seconds.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { AttandanceDetail } from './attandance-detail.model';

@Component({
    selector: 'app-minTime-allowSeconds-template-driven-validation-decorators',
    templateUrl: './min-time-allow-seconds.component.html'
})
export class MinTimeAllowSecondsTemplateDrivenValidationDecoratorsComponent implements OnInit {
    attandancedetail: AttandanceDetail
	
    constructor(
    ) { }

    ngOnInit() {
       this.attandancedetail= new AttandanceDetail()
    }
}

<div>
  <form #attandancedetailForm = "ngForm" [rxwebForm]="attandancedetailForm" [model]="attandancedetail">
    <div class="form-group">
      <label>Total Time Out</label>
	    <input type="text" name="totalOutTime" [(ngModel)]="attandancedetail.totalOutTime"  class="form-control" />

      <small class="form-text text-muted">This field allow seconds in input time.<br/></small>
	   <small class="form-text text-danger" *ngIf="attandancedetailForm.controls?.totalOutTime?.errors">{{attandancedetailForm.controls?.totalOutTime?.errors?.minTime.message}}<br/></small>	
    </div>
    <button [disabled]="!attandancedetailForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/minTime/allowSeconds/min-time-allow-seconds.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Total Time Out</label>
        <input id="name" class="form-control" v-model="attandanceDetailFormGroup.props.totalOutTime" type="text" name="name" />
          <small class="form-text text-muted">This field allow seconds in input time.<br/></small>
       <div v-if="attandanceDetailFormGroup.controls.totalOutTime.errors">
         <small class="form-text text-danger">{{attandanceDetailFormGroup.controls.totalOutTime.errors.minTime.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AttandanceDetail } from './attandanceDetail.model';

@Component
export default class MinTimeAllowSecondsComponent extends Vue {
 attandanceDetailFormGroup: IFormGroup<AttandanceDetail>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.attandanceDetailFormGroup = this.formBuilder.formGroup(AttandanceDetail) as IFormGroup<AttandanceDetail>;
   }
}
</script>
