// Examples/vue/rxweb-reactive-forms/src/components/odd/complete/odd-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Type</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.type" type="text" name="name" />
        <div v-if="userFormGroup.controls.type.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.type.errors.odd.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.number" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Number' then you need to add 'Type' input as 'Odd'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.number.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.number.errors.odd.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Odd Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.oddNumber" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Odd Number' then you need to add 'Type' input as 'Odd'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.oddNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.oddNumber.errors.odd.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Multiples of Odd Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.multiplesOfOddNumber" type="text" name="name" />
          <small class="form-text text-muted">you can enter only an odd number<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.multiplesOfOddNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.multiplesOfOddNumber.errors.odd.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Other Odd Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherOddNumber" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.otherOddNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherOddNumber.errors.odd.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class OddCompleteComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/odd/complete/odd-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-odd-complete-validator',
    templateUrl: './odd-complete.component.html'
})
export class OddCompleteValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            type:['',], 
            number:['', RxwebValidators.odd({conditionalExpression:(x,y) => x.type == "Odd"  })], 
            oddNumber:['', RxwebValidators.odd({conditionalExpression:'x => x.type == "Odd"' })], 
            multiplesOfOddNumber:['', RxwebValidators.odd({message:'{{0}} is not an odd number' })], 
            otherOddNumber:['', RxwebValidators.odd({messageKey:'oddMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Type</label>
      <input type="text" formControlName="type" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Number' or 'Odd Number', then you need to add 'Type' input as 'Odd'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.type.errors">{{userFormGroup.controls.type.errors.odd.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Number</label>
      <input type="text" formControlName="number" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Number' then you need to add 'Type' input as 'Odd'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.number.errors">{{userFormGroup.controls.number.errors.odd.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Odd Number</label>
      <input type="text" formControlName="oddNumber" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Odd Number' then you need to add 'Type' input as 'Odd'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.oddNumber.errors">{{userFormGroup.controls.oddNumber.errors.odd.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Multiples of Odd Number</label>
      <input type="text" formControlName="multiplesOfOddNumber" class="form-control"  />
      <small class="form-text text-muted">you can enter only an odd number<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.multiplesOfOddNumber.errors">{{userFormGroup.controls.multiplesOfOddNumber.errors.odd.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Other Odd Number</label>
      <input type="text" formControlName="otherOddNumber" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.otherOddNumber.errors">{{userFormGroup.controls.otherOddNumber.errors.odd.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
