// src/assets/examples/reactive-form-validators/template-driven/validation-directives/leapYear/messageKey/leap-year-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-leapYear-messageKey-template-driven-validation-directives',
    templateUrl: './leap-year-message-key.component.html'
})
export class LeapYearMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>Promotion Year</label>
	    <input type="text" name="promotionYear" [(ngModel)]="user.promotionYear"  class="form-control" [leapYear]="{'messageKey':'leapYearMessageKey'}"/>

      <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.promotionYear?.errors">{{userForm.controls?.promotionYear?.errors?.leapYear.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/leapYear/messageKey/leap-year-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Promotion Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.promotionYear" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
       <div v-if="userFormGroup.controls.promotionYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.promotionYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class LeapYearMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
