// Examples/vue/rxweb-reactive-forms/src/components/maxTime/fieldName/max-time-field-name.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Closing Time</label>
        <input id="name" class="form-control" v-model="attandanceDetailFormGroup.props.closingTime" type="text" name="name" />
        <div v-if="attandanceDetailFormGroup.controls.closingTime.errors">
         <small class="form-text text-danger">{{attandanceDetailFormGroup.controls.closingTime.errors.maxTime.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Exit Time</label>
        <input id="name" class="form-control" v-model="attandanceDetailFormGroup.props.exitTime" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
       <div v-if="attandanceDetailFormGroup.controls.exitTime.errors">
         <small class="form-text text-danger">{{attandanceDetailFormGroup.controls.exitTime.errors.maxTime.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AttandanceDetail } from './attandanceDetail.model';

@Component
export default class MaxTimeFieldNameComponent extends Vue {
 attandanceDetailFormGroup: IFormGroup<AttandanceDetail>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.attandanceDetailFormGroup = this.formBuilder.formGroup(AttandanceDetail) as IFormGroup<AttandanceDetail>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-decorators/maxTime/fieldName/max-time-field-name.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { AttandanceDetail } from './attandance-detail.model';

@Component({
    selector: 'app-maxTime-fieldName-template-driven-validation-decorators',
    templateUrl: './max-time-field-name.component.html'
})
export class MaxTimeFieldNameTemplateDrivenValidationDecoratorsComponent implements OnInit {
    attandancedetail: AttandanceDetail
	
    constructor(
    ) { }

    ngOnInit() {
       this.attandancedetail= new AttandanceDetail()
    }
}

<div>
  <form #attandancedetailForm = "ngForm" [rxwebForm]="attandancedetailForm" [model]="attandancedetail">
    <div class="form-group">
      <label>Closing Time</label>
	    <input type="text" name="closingTime" [(ngModel)]="attandancedetail.closingTime"  class="form-control" />

	   <small class="form-text text-danger" *ngIf="attandancedetailForm.controls?.closingTime?.errors">{{attandancedetailForm.controls?.closingTime?.errors?.maxTime.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Exit Time</label>
	    <input type="text" name="exitTime" [(ngModel)]="attandancedetail.exitTime"  class="form-control" />

      <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
	   <small class="form-text text-danger" *ngIf="attandancedetailForm.controls?.exitTime?.errors">{{attandancedetailForm.controls?.exitTime?.errors?.maxTime.message}}<br/></small>	
    </div>
    <button [disabled]="!attandancedetailForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
