// src/assets/examples/reactive-form-validators/validators/latLong/messageKey/lat-long-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-latLong-messageKey-validator',
    templateUrl: './lat-long-message-key.component.html'
})
export class LatLongMessageKeyValidatorComponent implements OnInit {
    countryFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.countryFormGroup = this.formBuilder.group({
            fourthCountry:['', RxwebValidators.latLong({messageKey:'latLongMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="countryFormGroup">
    <div class="form-group">
      <label>Fourth Country</label>
      <input type="text" formControlName="fourthCountry" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.fourthCountry.errors">{{countryFormGroup.controls.fourthCountry.errors.latLong.message}}<br/></small>
    </div>
    <button [disabled]="!countryFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/latLong/messageKey/lat-long-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Fourth Country</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.fourthCountry" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
       <div v-if="countryFormGroup.controls.fourthCountry.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.fourthCountry.errors.latLong.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Country } from './country.model';

@Component
export default class LatLongMessageKeyComponent extends Vue {
 countryFormGroup: IFormGroup<Country>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.countryFormGroup = this.formBuilder.formGroup(Country) as IFormGroup<Country>;
   }
}
</script>
