// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/template-driven/validation-directives/maxNumber/messageKey/max-number-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { SubjectDetails } from './subject-details.model';

@Component({
    selector: 'app-maxNumber-messageKey-template-driven-validation-directives',
    templateUrl: './max-number-message-key.component.html'
})
export class MaxNumberMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    subjectdetails: SubjectDetails
	
    constructor(
    ) { }

    ngOnInit() {
       this.subjectdetails= new SubjectDetails()
    }
}

<div>
  <form #subjectdetailsForm = "ngForm" [rxwebForm]="subjectdetailsForm" [model]="subjectdetails">
    <div class="form-group">
      <label>Discipline Marks</label>
	    <input type="text" name="disciplineMarks" [(ngModel)]="subjectdetails.disciplineMarks"  class="form-control" [rxmaxNumber]="{'value':50,'messageKey':'maxNumberMessageKey'}"/>

      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	   <small class="form-text text-danger" *ngIf="subjectdetailsForm.controls?.disciplineMarks?.errors">{{subjectdetailsForm.controls?.disciplineMarks?.errors?.maxNumber.message}}<br/></small>	
    </div>
    <button [disabled]="!subjectdetailsForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/maxNumber/messageKey/max-number-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Discipline Marks</label>
        <input id="name" class="form-control" v-model="subjectDetailsFormGroup.props.disciplineMarks" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="subjectDetailsFormGroup.controls.disciplineMarks.errors">
         <small class="form-text text-danger">{{subjectDetailsFormGroup.controls.disciplineMarks.errors.maxNumber.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { SubjectDetails } from './subjectDetails.model';

@Component
export default class MaxNumberMessageKeyComponent extends Vue {
 subjectDetailsFormGroup: IFormGroup<SubjectDetails>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.subjectDetailsFormGroup = this.formBuilder.formGroup(SubjectDetails) as IFormGroup<SubjectDetails>;
   }
}
</script>
