// Examples/vue/rxweb-reactive-forms/src/components/maxNumber/dynamic/max-number-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Subject Code</label>
        <input id="name" class="form-control" v-model="subjectDetailsFormGroup.props.subjectCode" type="text" name="name" />
        <div v-if="subjectDetailsFormGroup.controls.subjectCode.errors">
         <small class="form-text text-danger">{{subjectDetailsFormGroup.controls.subjectCode.errors.maxNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Maximum Marks for above subject code</label>
        <input id="name" class="form-control" v-model="subjectDetailsFormGroup.props.maximumMarks" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of Max Number on 'Maximum Marks' field, then enter the value '8CS5A' in 'Subject Code' textbox and you can enter maxNumber upto 100<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="subjectDetailsFormGroup.controls.maximumMarks.errors">
         <small class="form-text text-danger">{{subjectDetailsFormGroup.controls.maximumMarks.errors.maxNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Obtained Marks for above subject code</label>
        <input id="name" class="form-control" v-model="subjectDetailsFormGroup.props.obtainedMarks" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of Max Number on 'Obtained Marks' field, then enter the value '8CS5A' in 'Subject Code' textbox and you can enter maxNumber upto 100<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="subjectDetailsFormGroup.controls.obtainedMarks.errors">
         <small class="form-text text-danger">{{subjectDetailsFormGroup.controls.obtainedMarks.errors.maxNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Passing Marks</label>
        <input id="name" class="form-control" v-model="subjectDetailsFormGroup.props.passingMarks" type="text" name="name" />
          <small class="form-text text-muted">you can enter MaxNumber upto 50<br/></small>
       <div v-if="subjectDetailsFormGroup.controls.passingMarks.errors">
         <small class="form-text text-danger">{{subjectDetailsFormGroup.controls.passingMarks.errors.maxNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Practical Marks</label>
        <input id="name" class="form-control" v-model="subjectDetailsFormGroup.props.practicalMarks" type="text" name="name" />
          <small class="form-text text-muted">you can enter MaxNumber upto 70<br/></small>
         <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="subjectDetailsFormGroup.controls.practicalMarks.errors">
         <small class="form-text text-danger">{{subjectDetailsFormGroup.controls.practicalMarks.errors.maxNumber.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Discipline Marks</label>
        <input id="name" class="form-control" v-model="subjectDetailsFormGroup.props.disciplineMarks" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="subjectDetailsFormGroup.controls.disciplineMarks.errors">
         <small class="form-text text-danger">{{subjectDetailsFormGroup.controls.disciplineMarks.errors.maxNumber.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { SubjectDetails } from './subjectDetails.model';

@Component
export default class MaxNumberDynamicComponent extends Vue {
 subjectDetailsFormGroup: IFormGroup<SubjectDetails>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.subjectDetailsFormGroup = this.formBuilder.formGroup(SubjectDetails) as IFormGroup<SubjectDetails>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/maxNumber/dynamic/max-number-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-maxNumber-dynamic-validator',
    templateUrl: './max-number-dynamic.component.html'
})
export class MaxNumberDynamicValidatorComponent implements OnInit {
    subjectDetailsFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/maxNumber/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var subjectDetails = { subjectCode:'', maximumMarks:'', obtainedMarks:'', passingMarks:'', practicalMarks:'', disciplineMarks:'',  }
			this.subjectDetailsFormGroup = this.formBuilder.group(subjectDetails,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="subjectDetailsFormGroup"  [formGroup]="subjectDetailsFormGroup">
    <div class="form-group">
      <label>Subject Code</label>
      <input type="text" formControlName="subjectCode" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Maximum Marks' or 'Obtained Marks', then you need to add 'Type' input as '8CS5A'<br/></small>
      <small class="form-text text-danger" *ngIf="subjectDetailsFormGroup.controls.subjectCode.errors">{{subjectDetailsFormGroup.controls.subjectCode.errors.maxNumber.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Obtained Marks for above subject code</label>
      <input type="text" formControlName="obtainedMarks" class="form-control"  />
      <small class="form-text text-muted">To apply the validation of Max Number on 'Obtained Marks' field, then enter the value '8CS5A' in 'Subject Code' textbox and you can enter maxNumber upto 100<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="subjectDetailsFormGroup.controls.obtainedMarks.errors">{{subjectDetailsFormGroup.controls.obtainedMarks.errors.maxNumber.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Passing Marks</label>
      <input type="text" formControlName="passingMarks" class="form-control"  />
      <small class="form-text text-muted">you can enter MaxNumber upto 50<br/></small>
	<small class="form-text text-danger" *ngIf="subjectDetailsFormGroup.controls.passingMarks.errors">{{subjectDetailsFormGroup.controls.passingMarks.errors.maxNumber.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Practical Marks</label>
      <input type="text" formControlName="practicalMarks" class="form-control"  />
      <small class="form-text text-muted">you can enter MaxNumber upto 70<br/></small>
      <small class="form-text text-muted">Shows custom message<br/></small>
	<small class="form-text text-danger" *ngIf="subjectDetailsFormGroup.controls.practicalMarks.errors">{{subjectDetailsFormGroup.controls.practicalMarks.errors.maxNumber.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Discipline Marks</label>
      <input type="text" formControlName="disciplineMarks" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="subjectDetailsFormGroup.controls.disciplineMarks.errors">{{subjectDetailsFormGroup.controls.disciplineMarks.errors.maxNumber.message}}<br/></small>
    </div>
    <button [disabled]="!subjectDetailsFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
