// Examples/vue/rxweb-reactive-forms/src/components/minLength/dynamic/min-length-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Country Name</label>
        <input id="name" class="form-control" v-model="contactFormGroup.props.countryName" type="text" name="name" />
        <div v-if="contactFormGroup.controls.countryName.errors">
         <small class="form-text text-danger">{{contactFormGroup.controls.countryName.errors.minLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Mobile No.</label>
        <input id="name" class="form-control" v-model="contactFormGroup.props.mobileNo" type="text" name="name" />
          <small class="form-text text-muted">Minimum length upto 10 characters.<br/></small>
         <small class="form-text text-muted">Shows message from ReactiveFormConfig.<br/></small>
       <div v-if="contactFormGroup.controls.mobileNo.errors">
         <small class="form-text text-danger">{{contactFormGroup.controls.mobileNo.errors.minLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Land line No</label>
        <input id="name" class="form-control" v-model="contactFormGroup.props.landLineNo" type="text" name="name" />
          <small class="form-text text-muted">Minimum length upto 8 characters.<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="contactFormGroup.controls.landLineNo.errors">
         <small class="form-text text-danger">{{contactFormGroup.controls.landLineNo.errors.minLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Country Code</label>
        <input id="name" class="form-control" v-model="contactFormGroup.props.countryCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditionalExpression on 'Country Code', then enter 'India' in 'Country Name'<br/></small>
         <small class="form-text text-muted">Minimum length upto 3 characters.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="contactFormGroup.controls.countryCode.errors">
         <small class="form-text text-danger">{{contactFormGroup.controls.countryCode.errors.minLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>State Code</label>
        <input id="name" class="form-control" v-model="contactFormGroup.props.stateCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditionalExpression on 'State Code', then enter 'India' in 'Country Name'<br/></small>
         <small class="form-text text-muted">Minimum length upto 3 characters.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="contactFormGroup.controls.stateCode.errors">
         <small class="form-text text-danger">{{contactFormGroup.controls.stateCode.errors.minLength.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>State Name</label>
        <input id="name" class="form-control" v-model="contactFormGroup.props.stateName" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="contactFormGroup.controls.stateName.errors">
         <small class="form-text text-danger">{{contactFormGroup.controls.stateName.errors.minLength.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Contact } from './contact.model';

@Component
export default class MinLengthDynamicComponent extends Vue {
 contactFormGroup: IFormGroup<Contact>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.contactFormGroup = this.formBuilder.formGroup(Contact) as IFormGroup<Contact>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/minLength/dynamic/min-length-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-minLength-dynamic-validator',
    templateUrl: './min-length-dynamic.component.html'
})
export class MinLengthDynamicValidatorComponent implements OnInit {
    contactFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/validators/minLength/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var contact = { countryName:'', mobileNo:'', landLineNo:'', countryCode:'', stateCode:'', stateName:'',  }
			this.contactFormGroup = this.formBuilder.group(contact,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="contactFormGroup"  [formGroup]="contactFormGroup">
    <div class="form-group">
      <label>Country Name</label>
      <input type="text" formControlName="countryName" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Country Code' or 'State Code', then you need to add 'Country Name' input as 'India'<br/></small>
      <small class="form-text text-danger" *ngIf="contactFormGroup.controls.countryName.errors">{{contactFormGroup.controls.countryName.errors.minLength.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Mobile No.</label>
      <input type="text" formControlName="mobileNo" class="form-control"  />
      <small class="form-text text-muted">Minimum length upto 10 characters.<br/></small>
      <small class="form-text text-muted">Shows message from ReactiveFormConfig.<br/></small>
	<small class="form-text text-danger" *ngIf="contactFormGroup.controls.mobileNo.errors">{{contactFormGroup.controls.mobileNo.errors.minLength.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Land line No</label>
      <input type="text" formControlName="landLineNo" class="form-control"  />
      <small class="form-text text-muted">Minimum length upto 8 characters.<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="contactFormGroup.controls.landLineNo.errors">{{contactFormGroup.controls.landLineNo.errors.minLength.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>State Code</label>
      <input type="text" formControlName="stateCode" class="form-control"  />
      <small class="form-text text-muted">To apply validation here, write 'India' in 'Country Name' textbox because it is conditional expression.<br/></small>
      <small class="form-text text-muted">Minimum length upto 3 characters.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="contactFormGroup.controls.stateCode.errors">{{contactFormGroup.controls.stateCode.errors.minLength.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>State Name</label>
      <input type="text" formControlName="stateName" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="contactFormGroup.controls.stateName.errors">{{contactFormGroup.controls.stateName.errors.minLength.message}}<br/></small>
    </div>
    <button [disabled]="!contactFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
