// Examples/vue/rxweb-reactive-forms/src/components/dataUri/messageKey/data-uri-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Pdf Data Uri</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.pdfDataUri" type="text" name="name" />
          <small class="form-text text-muted">Custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.pdfDataUri.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.pdfDataUri.errors.dataUri.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class DataUriMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/dataUri/messageKey/data-uri-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-dataUri-messageKey',
    templateUrl: './data-uri-message-key.component.html'
})
export class DataUriMessageKeyComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder    ) { }

    ngOnInit() {
        let user = new User();
        this.userFormGroup = this.formBuilder.formGroup(user);
    }
}
