// src/assets/examples/reactive-form-validators/decorators/date/edit/date-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { UserInfo } from './user-info.model';

@Component({
    selector: 'app-date-edit',
    templateUrl: './date-edit.component.html'
})
export class DateEditComponent implements OnInit {
    userInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/date/edit/user-info-data.json?v=' + environment.appVersion).subscribe(userInfo => {
            this.userInfoFormGroup = this.formBuilder.formGroup<UserInfo>(UserInfo,userInfo);
        })
    }
}

<div>
  <form  *ngIf="userInfoFormGroup"  [formGroup]="userInfoFormGroup">
    <div class="form-group">
      <label>Birth Date</label>
      <input type="text" formControlName="birthDate" class="form-control"  />
      <small class="form-text text-muted">You must enter a valid date only<br/></small>
     <small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.birthDate.errors">{{userInfoFormGroup.controls.birthDate.errors.date.message}}<br/></small>	
    </div>
    <button [disabled]="!userInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/date/edit/date-edit.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Birth Date</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.birthDate" type="text" name="name" />
          <small class="form-text text-muted">You must enter a valid date only<br/></small>
       <div v-if="userInfoFormGroup.controls.birthDate.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.birthDate.errors.date.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class DateEditComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>
