// Examples/vue/rxweb-reactive-forms/src/components/url/dynamic/url-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Admin Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.adminWebsiteUrl" type="text" name="name" />
        <div v-if="userFormGroup.controls.adminWebsiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.adminWebsiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>QA Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.qaWebsiteUrl" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'QA Website Url' then you need to add 'admin Website Url' input as 'https://google.co.in'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.qaWebsiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.qaWebsiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Customer Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.customerWebsiteUrl" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Customer Website Url' then you need to add 'admin Website Url' input as 'https://google.co.in'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.customerWebsiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.customerWebsiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Maintenance Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.maintenanceWebSiteUrl" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
       <div v-if="userFormGroup.controls.maintenanceWebSiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.maintenanceWebSiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Deployed Website Url</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.deployedWebSiteUrl" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message based on message key<br/></small>
       <div v-if="userFormGroup.controls.deployedWebSiteUrl.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.deployedWebSiteUrl.errors.url.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class UrlDynamicComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/url/dynamic/url-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-url-dynamic-validator',
    templateUrl: './url-dynamic.component.html'
})
export class UrlDynamicValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/url/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var user = { adminWebsiteUrl:'', qaWebsiteUrl:'', customerWebsiteUrl:'', maintenanceWebSiteUrl:'', deployedWebSiteUrl:'',  }
			this.userFormGroup = this.formBuilder.group(user,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Admin Website Url</label>
      <input type="text" formControlName="adminWebsiteUrl" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'QA Website Url' or 'Customer Website Url', then you need to add 'Admin Website Url' input as 'https://google.co.in'<br/></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.adminWebsiteUrl.errors">{{userFormGroup.controls.adminWebsiteUrl.errors.url.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Customer Website Url</label>
      <input type="text" formControlName="customerWebsiteUrl" class="form-control"  />
      <small class="form-text text-muted">Enter 'https://google.co.in' in Admin Website Url textbox above for apply validation<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.customerWebsiteUrl.errors">{{userFormGroup.controls.customerWebsiteUrl.errors.url.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Maintenance Website Url</label>
      <input type="text" formControlName="maintenanceWebSiteUrl" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.maintenanceWebSiteUrl.errors">{{userFormGroup.controls.maintenanceWebSiteUrl.errors.url.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Deployed Website Url</label>
      <input type="text" formControlName="deployedWebSiteUrl" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.deployedWebSiteUrl.errors">{{userFormGroup.controls.deployedWebSiteUrl.errors.url.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
