// Examples/vue/rxweb-reactive-forms/src/components/ascii/dynamic/ascii-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Language</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.language" type="text" name="name" />
        <div v-if="userFormGroup.controls.language.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.language.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Number Ascii Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.numberAsciiCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Number Ascii Code' then you need to add 'Language' input as 'Java'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.numberAsciiCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.numberAsciiCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Alphabet Ascii Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.alphabetAsciiCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Alphabet Ascii Code' then you need to add 'Language' input as 'Java'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.alphabetAsciiCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.alphabetAsciiCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Special Character Ascii Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.specialCharAsciiCode" type="text" name="name" />
          <small class="form-text text-muted">enter Ascii Code only<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.specialCharAsciiCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.specialCharAsciiCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Digital Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.digitalCode" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.digitalCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.digitalCode.errors.ascii.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class AsciiDynamicComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/ascii/dynamic/ascii-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';
import { FormBuilderConfiguration,} from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-ascii-dynamic',
    templateUrl: './ascii-dynamic.component.html'
})
export class AsciiDynamicComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        let user = new User();
        let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/ascii/dynamic/dynamic.json?v=' + environment.appVersion).subscribe(dynamic => {
            formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			this.userFormGroup = this.formBuilder.formGroup(user,formBuilderConfiguration);
        })
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Language</label>
      <input type="text" formControlName="language" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Number Ascii Code' or 'Alphabet Ascii Code', then you need to add 'Language' input as 'Java'<br/></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.language.errors">{{userFormGroup.controls.language.errors.ascii.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Alphabet Ascii Code</label>
      <input type="text" formControlName="alphabetAsciiCode" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Alphabet Ascii Code' then you need to add 'Language' input as 'Java'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.alphabetAsciiCode.errors">{{userFormGroup.controls.alphabetAsciiCode.errors.ascii.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Special Character Ascii Code</label>
      <input type="text" formControlName="specialCharAsciiCode" class="form-control"  />
      <small class="form-text text-muted">enter Ascii Code only<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.specialCharAsciiCode.errors">{{userFormGroup.controls.specialCharAsciiCode.errors.ascii.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Digital Code</label>
      <input type="text" formControlName="digitalCode" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.digitalCode.errors">{{userFormGroup.controls.digitalCode.errors.ascii.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
