// Examples/vue/rxweb-reactive-forms/src/components/lessThanEqualTo/messageKey/less-than-equal-to-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Discipline Marks</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.disciplineMarks" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userFormGroup.controls.disciplineMarks.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.disciplineMarks.errors.lessThanEqualTo.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class LessThanEqualToMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/lessThanEqualTo/messageKey/less-than-equal-to-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-lessThanEqualTo-messageKey-validator',
    templateUrl: './less-than-equal-to-message-key.component.html'
})
export class LessThanEqualToMessageKeyValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            totalMarks:['',], 
            disciplineMarks:['', RxwebValidators.lessThanEqualTo({fieldName:'totalMarks'  ,messageKey:'lessThanEqualToMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Discipline Marks</label>
      <input type="text" formControlName="disciplineMarks" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.disciplineMarks.errors">{{userFormGroup.controls.disciplineMarks.errors.lessThanEqualToMessageKey.message}}<br/></small>		
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
