// src/assets/examples/reactive-form-validators/validators/pattern/complete/pattern-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-pattern-complete-validator',
    templateUrl: './pattern-complete.component.html'
})
export class PatternCompleteValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            userName:['', RxwebValidators.pattern({expression:{'onlyAlpha': /^[A-Za-z]+$/} })], 
            zipCode:['', RxwebValidators.pattern({expression:{'zipCode':/^[0-9]{5}(?:-[0-9]{4})?$/ }  ,message:'Zip code should match 12345 or 12345-6789' })], 
            contactNumber:['', RxwebValidators.pattern({expression:{'onlyDigit': /^[0-9]*$/}  ,conditionalExpression:(x,y) => x.userName == "Bharat"  })], 
            age:['', RxwebValidators.pattern({expression:{'onlyDigit': /^[0-9]*$/}  ,conditionalExpression:'x => x.userName=="Bharat"' })], 
            pinCode:['', RxwebValidators.pattern({expression:{'pinCode':/^[1-9][0-9]{5}$/ }  ,messageKey:'patternMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>User Name</label>
      <input type="text" formControlName="userName" class="form-control"  />
      <small class="form-text text-muted">It checked that username match alpha regex or not<br/></small>
      <small class="form-text text-muted">If you want to apply conditional validation on 'Contact Number' or 'Age', then you need to add 'userName' input as 'Bharat<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.userName.errors">{{userFormGroup.controls.userName.errors.onlyAlpha.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Zip Code</label>
      <input type="text" formControlName="zipCode" class="form-control"  />
      <small class="form-text text-muted">It checked that zipcode match zipcode regex or not <br/></small>
      <small class="form-text text-muted">Shows custom message<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.zipCode.errors">{{userFormGroup.controls.zipCode.errors.zipCode.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Contact Number</label>
      <input type="text" formControlName="contactNumber" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Number' then you need to add 'UserName' input as 'Bharat'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.contactNumber.errors">{{userFormGroup.controls.contactNumber.errors.onlyDigit.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Age</label>
      <input type="text" formControlName="age" class="form-control"  />
      <small class="form-text text-muted">It checked that age match with digit regex or not and it conditionaly applied when userName is Bharat<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.age.errors">{{userFormGroup.controls.age.errors.onlyDigit.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Pin Code</label>
      <input type="text" formControlName="pinCode" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.pinCode.errors">{{userFormGroup.controls.pinCode.errors.pinCode.message}}<br/></small>	
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/pattern/complete/pattern-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>User Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.userName" type="text" name="name" />
          <small class="form-text text-muted">It checked that username match alpha regex or not<br/></small>
       <div v-if="userFormGroup.controls.userName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.userName.errors.pattern.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Zip Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.zipCode" type="text" name="name" />
          <small class="form-text text-muted">It checked that zipcode match zipcode regex or not <br/></small>
         <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="userFormGroup.controls.zipCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.zipCode.errors.pattern.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Contact Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.contactNumber" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Contact Number' then you need to add 'UserName' input as 'Bharat'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.contactNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.contactNumber.errors.pattern.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.age" type="text" name="name" />
          <small class="form-text text-muted">It checked that age match with digit regex or not and it conditionaly applied when userName is Bharat<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.age.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.age.errors.pattern.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Pin Code</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.pinCode" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userFormGroup.controls.pinCode.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.pinCode.errors.pattern.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class PatternCompleteComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
