// src/assets/examples/reactive-form-validators/validators/leapYear/complete/leap-year-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-leapYear-complete-validator',
    templateUrl: './leap-year-complete.component.html'
})
export class LeapYearCompleteValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            name:['',], 
            birthYear:['', RxwebValidators.leapYear({conditionalExpression:(x,y) => x.name == "Bharat"  })], 
            admissionYear:['', RxwebValidators.leapYear({conditionalExpression:'x => x.name == "Bharat"' })], 
            joiningYear:['', RxwebValidators.leapYear({message:'{{0}} is not a leap year' })], 
            promotionYear:['', RxwebValidators.leapYear({messageKey:'leapYearMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Name</label>
      <input type="text" formControlName="name" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Birth Year' or 'Admission Date', then you need to add 'Name' input as 'Bharat'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.name.errors">{{userFormGroup.controls.name.errors.leapYear.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Birth Year</label>
      <input type="text" formControlName="birthYear" class="form-control"  />
      <small class="form-text text-muted">To apply the validation of Leap Year on 'Birth Year' field, then enter the value 'Bharat' in 'Name' textbox<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.birthYear.errors">{{userFormGroup.controls.birthYear.errors.leapYear.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Admission Year</label>
      <input type="text" formControlName="admissionYear" class="form-control"  />
      <small class="form-text text-muted">To apply the validation of leap on 'Admission Year' field, then enter the value 'Bharat' in 'Name' textbox<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.admissionYear.errors">{{userFormGroup.controls.admissionYear.errors.leapYear.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Joining Year</label>
      <input type="text" formControlName="joiningYear" class="form-control"  />
      <small class="form-text text-muted">you can enter only a leap year<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.joiningYear.errors">{{userFormGroup.controls.joiningYear.errors.leapYear.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Promotion Year</label>
      <input type="text" formControlName="promotionYear" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.promotionYear.errors">{{userFormGroup.controls.promotionYear.errors.leapYear.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/leapYear/complete/leap-year-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.name" type="text" name="name" />
        <div v-if="userFormGroup.controls.name.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.name.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Birth Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.birthYear" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of leapYear on 'Birth Year' field, then enter 'Bharat' in 'Name' textbox<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.birthYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.birthYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Admission Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.admissionYear" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of leapYear on 'Admission Year' field, then enter 'Bharat' in 'Name' textbox<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.admissionYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.admissionYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Joining Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.joiningYear" type="text" name="name" />
          <small class="form-text text-muted">you can enter only a leap year<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.joiningYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.joiningYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Promotion Year</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.promotionYear" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
       <div v-if="userFormGroup.controls.promotionYear.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.promotionYear.errors.leapYear.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class LeapYearCompleteComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
