// src/assets/examples/reactive-form-validators/validators/factor/dynamic/factor-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';
import { HttpClient } from '@angular/common/http';
import { FormBuilderConfiguration,RxFormBuilder} from '@rxweb/reactive-form-validators';
import { environment } from 'src/environments/environment';

@Component({
    selector: 'app-factor-dynamic-validator',
    templateUrl: './factor-dynamic.component.html'
})
export class FactorDynamicValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: RxFormBuilder , private http: HttpClient )
	{ }

    ngOnInit() {
		let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('assets/examples/reactive-form-validators/validators/factor/dynamic/dynamic.json?v='+environment.appVersion).subscribe(dynamic => {
			formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			var user = { firstNumber:'', fifthNumber:'', secondNumber:'', thirdNumber:'', fourthNumber:'', sixthNumber:'', seventhNumber:'',  }
			this.userFormGroup = this.formBuilder.group(user,formBuilderConfiguration);
		})
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>First Number</label>
      <input type="text" formControlName="firstNumber" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Second Number' or 'Third Number', then you need to add 'First Number' input as '25'<br/></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.firstNumber.errors">{{userFormGroup.controls.firstNumber.errors.factor.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Fifth Number</label>
      <input type="text" formControlName="fifthNumber" class="form-control"  />
      <small class="form-text text-muted">To apply the validation of factor on 'Fifth Number' field<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.fifthNumber.errors">{{userFormGroup.controls.fifthNumber.errors.factor.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Third Number</label>
      <input type="text" formControlName="thirdNumber" class="form-control"  />
      <small class="form-text text-muted">To apply the validation of factor on 'Fourth Number' field, then enter the value '25' in 'First Number' textbox<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.thirdNumber.errors">{{userFormGroup.controls.thirdNumber.errors.factor.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Fourth Number</label>
      <input type="text" formControlName="fourthNumber" class="form-control"  />
      <small class="form-text text-muted">you can enter only factors of 50<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.fourthNumber.errors">{{userFormGroup.controls.fourthNumber.errors.factor.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Sixth Number</label>
      <input type="text" formControlName="sixthNumber" class="form-control"  />
      <small class="form-text text-muted">you can enter only factors of 50<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.sixthNumber.errors">{{userFormGroup.controls.sixthNumber.errors.factor.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Seventh Number</label>
      <input type="text" formControlName="seventhNumber" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.seventhNumber.errors">{{userFormGroup.controls.seventhNumber.errors.factor.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/factor/dynamic/factor-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>First Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.firstNumber" type="text" name="name" />
        <div v-if="userFormGroup.controls.firstNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.firstNumber.errors.factor.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Fifth Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.fifthNumber" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of factor on 'Fifth Number' field<br/></small>
       <div v-if="userFormGroup.controls.fifthNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.fifthNumber.errors.factor.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Second Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.secondNumber" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of factor on 'Second Number' field, then enter the value '25' in 'First Number' textbox<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.secondNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.secondNumber.errors.factor.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Third Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.thirdNumber" type="text" name="name" />
          <small class="form-text text-muted">To apply the validation of factor on 'Third Number' field, then enter the value '25' in 'First Number' textbox<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.thirdNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.thirdNumber.errors.factor.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Fourth Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.fourthNumber" type="text" name="name" />
          <small class="form-text text-muted">you can enter only factors of 50<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.fourthNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.fourthNumber.errors.factor.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Sixth Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.sixthNumber" type="text" name="name" />
          <small class="form-text text-muted">you can enter only factors of 30<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.sixthNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.sixthNumber.errors.factor.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Seventh Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.seventhNumber" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.seventhNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.seventhNumber.errors.factor.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class FactorDynamicComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
