// Examples/vue/rxweb-reactive-forms/src/components/primeNumber/messageKey/prime-number-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Fourth Number</label>
        <input id="name" class="form-control" v-model="numberInfoFormGroup.props.fourthNumber" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message using messageKey<br/></small>
       <div v-if="numberInfoFormGroup.controls.fourthNumber.errors">
         <small class="form-text text-danger">{{numberInfoFormGroup.controls.fourthNumber.errors.primeNumber.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { NumberInfo } from './numberInfo.model';

@Component
export default class PrimeNumberMessageKeyComponent extends Vue {
 numberInfoFormGroup: IFormGroup<NumberInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.numberInfoFormGroup = this.formBuilder.formGroup(NumberInfo) as IFormGroup<NumberInfo>;
   }
}
</script>

// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/decorators/primeNumber/messageKey/prime-number-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { NumberInfo } from './number-info.model';

@Component({
    selector: 'app-primeNumber-messageKey',
    templateUrl: './prime-number-message-key.component.html'
})
export class PrimeNumberMessageKeyComponent implements OnInit {
    numberInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder    ) { }

    ngOnInit() {
        let numberInfo = new NumberInfo();
        this.numberInfoFormGroup = this.formBuilder.formGroup(numberInfo);
    }
}
