// Examples/vue/rxweb-reactive-forms/src/components/mac/messageKey/mac-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Server MAC Address</label>
        <input id="name" class="form-control" v-model="macAddressInfoFormGroup.props.serverMacAddress" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="macAddressInfoFormGroup.controls.serverMacAddress.errors">
         <small class="form-text text-danger">{{macAddressInfoFormGroup.controls.serverMacAddress.errors.mac.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { MacAddressInfo } from './macAddressInfo.model';

@Component
export default class MacMessageKeyComponent extends Vue {
 macAddressInfoFormGroup: IFormGroup<MacAddressInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.macAddressInfoFormGroup = this.formBuilder.formGroup(MacAddressInfo) as IFormGroup<MacAddressInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/template-driven/validation-directives/mac/messageKey/mac-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { MacAddressInfo } from './mac-address-info.model';

@Component({
    selector: 'app-mac-messageKey-template-driven-validation-directives',
    templateUrl: './mac-message-key.component.html'
})
export class MacMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    macaddressinfo: MacAddressInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.macaddressinfo= new MacAddressInfo()
    }
}

<div>
  <form #macaddressinfoForm = "ngForm" [rxwebForm]="macaddressinfoForm" [model]="macaddressinfo">
    <div class="form-group">
      <label>Server MAC Address</label>
	    <input type="text" name="serverMacAddress" [(ngModel)]="macaddressinfo.serverMacAddress"  class="form-control" [mac]="{'messageKey':'macMessageKey'}"/>

      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	   <small class="form-text text-danger" *ngIf="macaddressinfoForm.controls?.serverMacAddress?.errors">{{macaddressinfoForm.controls?.serverMacAddress?.errors?.mac.message}}<br/></small>	
    </div>
    <button [disabled]="!macaddressinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
