// Examples/vue/rxweb-reactive-forms/src/components/password/dynamic/password-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>New Password</label>
        <input id="name" class="form-control" v-model="loginInfoFormGroup.props.newPassword" type="text" name="name" />
        <div v-if="loginInfoFormGroup.controls.newPassword.errors">
         <small class="form-text text-danger">{{loginInfoFormGroup.controls.newPassword.errors.password.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Old Password</label>
        <input id="name" class="form-control" v-model="loginInfoFormGroup.props.oldPassword" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message<br/></small>
       <div v-if="loginInfoFormGroup.controls.oldPassword.errors">
         <small class="form-text text-danger">{{loginInfoFormGroup.controls.oldPassword.errors.password.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Confirm Password</label>
        <input id="name" class="form-control" v-model="loginInfoFormGroup.props.confirmPassword" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message using message key<br/></small>
       <div v-if="loginInfoFormGroup.controls.confirmPassword.errors">
         <small class="form-text text-danger">{{loginInfoFormGroup.controls.confirmPassword.errors.password.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { LoginInfo } from './loginInfo.model';

@Component
export default class PasswordDynamicComponent extends Vue {
 loginInfoFormGroup: IFormGroup<LoginInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.loginInfoFormGroup = this.formBuilder.formGroup(LoginInfo) as IFormGroup<LoginInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/password/dynamic/password-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';
import { FormBuilderConfiguration,} from '@rxweb/reactive-form-validators';

import { LoginInfo } from './login-info.model';

@Component({
    selector: 'app-password-dynamic',
    templateUrl: './password-dynamic.component.html'
})
export class PasswordDynamicComponent implements OnInit {
    loginInfoFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        let loginInfo = new LoginInfo();
        let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/password/dynamic/dynamic.json?v=' + environment.appVersion).subscribe(dynamic => {
            formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			this.loginInfoFormGroup = this.formBuilder.formGroup(loginInfo,formBuilderConfiguration);
        })
    }
}

<div>
  <form  *ngIf="loginInfoFormGroup"  [formGroup]="loginInfoFormGroup">
    <div class="form-group">
      <label>New Password</label>
      <input type="text" formControlName="newPassword" class="form-control"  />
	<small class="form-text text-danger" *ngIf="loginInfoFormGroup.controls.newPassword.errors">{{loginInfoFormGroup.controls.newPassword.errors.password.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Old Password</label>
      <input type="text" formControlName="oldPassword" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message<br/></small>
	<small class="form-text text-danger" *ngIf="loginInfoFormGroup.controls.oldPassword.errors">{{loginInfoFormGroup.controls.oldPassword.errors.password.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Confirm Password</label>
      <input type="text" formControlName="confirmPassword" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message using message key<br/></small>
	<small class="form-text text-danger" *ngIf="loginInfoFormGroup.controls.confirmPassword.errors">{{loginInfoFormGroup.controls.confirmPassword.errors.password.message}}<br/></small>
    </div>
    <button [disabled]="!loginInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
