// Examples/vue/rxweb-reactive-forms/src/components/hexColor/messageKey/hex-color-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Title Hexcode</label>
        <input id="name" class="form-control" v-model="hexcolorInfoFormGroup.props.titleHexcolorCode" type="text" name="name" />
          <small class="form-text text-muted">Custom message based on message key<br/></small>
       <div v-if="hexcolorInfoFormGroup.controls.titleHexcolorCode.errors">
         <small class="form-text text-danger">{{hexcolorInfoFormGroup.controls.titleHexcolorCode.errors.hexColor.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { HexcolorInfo } from './hexcolorInfo.model';

@Component
export default class HexColorMessageKeyComponent extends Vue {
 hexcolorInfoFormGroup: IFormGroup<HexcolorInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.hexcolorInfoFormGroup = this.formBuilder.formGroup(HexcolorInfo) as IFormGroup<HexcolorInfo>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/validators/hexColor/messageKey/hex-color-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-hexColor-messageKey-validator',
    templateUrl: './hex-color-message-key.component.html'
})
export class HexColorMessageKeyValidatorComponent implements OnInit {
    hexcolorInfoFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.hexcolorInfoFormGroup = this.formBuilder.group({
            titleHexcolorCode:['', RxwebValidators.hexColor({messageKey:'hexColorMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="hexcolorInfoFormGroup">
    <div class="form-group">
      <label>Title Hexcode</label>
      <input type="text" formControlName="titleHexcolorCode" class="form-control"  />
      <small class="form-text text-muted">Custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="hexcolorInfoFormGroup.controls.titleHexcolorCode.errors">{{hexcolorInfoFormGroup.controls.titleHexcolorCode.errors.hexColor.message}}<br/></small>
    </div>
    <button [disabled]="!hexcolorInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
