// src/assets/examples/reactive-form-validators/decorators/notEmpty/conditionalExpression/not-empty-conditional-expression.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-notEmpty-conditionalExpression',
    templateUrl: './not-empty-conditional-expression.component.html'
})
export class NotEmptyConditionalExpressionComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder    ) { }

    ngOnInit() {
        let user = new User();
        this.userFormGroup = this.formBuilder.formGroup(user);
    }
}

<div>
  <form  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>First Name</label>
      <input type="text" formControlName="firstName" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Middle Name' or 'Last Name', then you need to add 'First Name' input as 'Bharat'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.firstName.errors">{{userFormGroup.controls.firstName.errors.notEmpty.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Last Name</label>
      <input type="text" formControlName="lastName" class="form-control"  />
      <small class="form-text text-muted">Conditional notEmpty Validation.<br/></small>
      <small class="form-text text-muted">Conditional validation will be applied if the 'FirstName' field have value of 'Bharat'<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.lastName.errors">{{userFormGroup.controls.lastName.errors.notEmpty.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Middle Name</label>
      <input type="text" formControlName="middleName" class="form-control"  />
      <small class="form-text text-muted">Conditional validation will be applied if the 'FirstName' field have value of 'Bharat'<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
     <small class="form-text text-danger" *ngIf="userFormGroup.controls.middleName.errors">{{userFormGroup.controls.middleName.errors.notEmpty.message}}<br/></small>	
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/notEmpty/conditionalExpression/not-empty-conditional-expression.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>First Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.firstName" type="text" name="name" />
        <div v-if="userFormGroup.controls.firstName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.firstName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Last Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.lastName" type="text" name="name" />
          <small class="form-text text-muted">Conditional validation will be applied if the user enter 'Bharat' in 'First Name' field <br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.lastName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.lastName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Middle Name</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.middleName" type="text" name="name" />
          <small class="form-text text-muted">Conditional validation will be applied if the user enter 'Bharat' in 'FirstName' field <br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.middleName.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.middleName.errors.notEmpty.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class NotEmptyConditionalExpressionComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
