// src/assets/examples/reactive-form-validators/decorators/latitude/messageKey/latitude-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { RxFormBuilder } from '@rxweb/reactive-form-validators';

import { Country } from './country.model';

@Component({
    selector: 'app-latitude-messageKey',
    templateUrl: './latitude-message-key.component.html'
})
export class LatitudeMessageKeyComponent implements OnInit {
    countryFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder    ) { }

    ngOnInit() {
        let country = new Country();
        this.countryFormGroup = this.formBuilder.formGroup(country);
    }
}

<div>
  <form  [formGroup]="countryFormGroup">
    <div class="form-group">
      <label>Fourth Country Latitude</label>
      <input type="text" formControlName="fourthCountryLatitude" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="countryFormGroup.controls.fourthCountryLatitude.errors">{{countryFormGroup.controls.fourthCountryLatitude.errors.latitude.message}}<br/></small>
    </div>
    <button [disabled]="!countryFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/latitude/messageKey/latitude-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Fourth Country Latitude</label>
        <input id="name" class="form-control" v-model="countryFormGroup.props.fourthCountryLatitude" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="countryFormGroup.controls.fourthCountryLatitude.errors">
         <small class="form-text text-danger">{{countryFormGroup.controls.fourthCountryLatitude.errors.latitude.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Country } from './country.model';

@Component
export default class LatitudeMessageKeyComponent extends Vue {
 countryFormGroup: IFormGroup<Country>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.countryFormGroup = this.formBuilder.formGroup(Country) as IFormGroup<Country>;
   }
}
</script>
