// src/assets/examples/reactive-form-validators/validators/greaterThan/messageKey/greater-than-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-greaterThan-messageKey-validator',
    templateUrl: './greater-than-message-key.component.html'
})
export class GreaterThanMessageKeyValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            age:['',], 
            joiningAge:['', RxwebValidators.greaterThan({fieldName:'age'  ,messageKey:'greaterThanMessageKey' })], 
        });
    }
}

<div>
  <form [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Age</label>
      <input type="text" formControlName="age" class="form-control" />
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.age.errors">{{userFormGroup.controls.age.errors.greaterThan.message}}<br /></small>
    </div>
    <div class="form-group">
      <label>Joining Age</label>
      <input type="text" formControlName="joiningAge" class="form-control" />
      <small class="form-text text-muted">Shows custom message based on message key<br /></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.joiningAge.errors">{{userFormGroup.controls.joiningAge.errors.greaterThan.message}}<br /></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/greaterThan/messageKey/greater-than-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Joining Age</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.joiningAge" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userFormGroup.controls.joiningAge.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.joiningAge.errors.greaterThan.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class GreaterThanMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
