// Examples/vue/rxweb-reactive-forms/src/components/numeric/isFormat/numeric-is-format.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Total Amount</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.totalAmount" type="text" name="name" />
        <div v-if="userInfoFormGroup.controls.totalAmount.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.totalAmount.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class NumericIsFormatComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>

// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/template-driven/validation-directives/numeric/isFormat/numeric-is-format.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { UserInfo } from './user-info.model';

@Component({
    selector: 'app-numeric-isFormat-template-driven-validation-directives',
    templateUrl: './numeric-is-format.component.html'
})
export class NumericIsFormatTemplateDrivenValidationDirectivesComponent implements OnInit {
    userinfo: UserInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.userinfo= new UserInfo()
    }
}

<div>
  <form #userinfoForm = "ngForm" [rxwebForm]="userinfoForm" [model]="userinfo">
    <div class="form-group">
      <label>Total Amount</label>
	    <input type="text" name="totalAmount" [(ngModel)]="userinfo.totalAmount"  class="form-control" [numeric]="{'isFormat':true}"/>

	   <small class="form-text text-danger" *ngIf="userinfoForm.controls?.totalAmount?.errors">{{userinfoForm.controls?.totalAmount?.errors?.numeric.message}}<br/></small>	
    </div>
    <button [disabled]="!userinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
