// src/assets/examples/reactive-form-validators/validators/alphaNumeric/complete/alpha-numeric-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-alphaNumeric-complete-validator',
    templateUrl: './alpha-numeric-complete.component.html'
})
export class AlphaNumericCompleteValidatorComponent implements OnInit {
    locationFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.locationFormGroup = this.formBuilder.group({
            areaName:['', RxwebValidators.alphaNumeric()], 
            flatAddress:['', RxwebValidators.alphaNumeric({allowWhiteSpace:true })], 
            postalAddress:['', RxwebValidators.alphaNumeric({message:'Please enter only alphanumerics, special characters are not allowed.' })], 
            countryCode:['', RxwebValidators.alphaNumeric({conditionalExpression:(x,y) => x.areaName == "Delhi"  })], 
            cityCode:['', RxwebValidators.alphaNumeric({conditionalExpression:'x => x.areaName =="Delhi"' })], 
            colonyName:['', RxwebValidators.alphaNumeric({messageKey:'alphaNumericMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="locationFormGroup">
    <div class="form-group">
      <label>Area Name</label>
      <input type="text" formControlName="areaName" class="form-control"  />
     <small class="form-text text-danger" *ngIf="locationFormGroup.controls.areaName.errors">{{locationFormGroup.controls.areaName.errors.alphaNumeric.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Flat Address</label>
      <input type="text" formControlName="flatAddress" class="form-control"  />
      <small class="form-text text-muted">This allowed whitespace in alpha Numeric validation<br/></small>
	<small class="form-text text-danger" *ngIf="locationFormGroup.controls.flatAddress.errors">{{locationFormGroup.controls.flatAddress.errors.alphaNumeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Postal Address</label>
      <input type="text" formControlName="postalAddress" class="form-control"  />
      <small class="form-text text-muted">Shows custom message<br/></small>
	<small class="form-text text-danger" *ngIf="locationFormGroup.controls.postalAddress.errors">{{locationFormGroup.controls.postalAddress.errors.alphaNumeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Country Code</label>
      <input type="text" formControlName="countryCode" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on this field then you need to add 'areaName' input as 'Delhi'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
	<small class="form-text text-danger" *ngIf="locationFormGroup.controls.countryCode.errors">{{locationFormGroup.controls.countryCode.errors.alphaNumeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>City Code</label>
      <input type="text" formControlName="cityCode" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on this field then you need to add 'areaName' input as 'Delhi'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="locationFormGroup.controls.cityCode.errors">{{locationFormGroup.controls.cityCode.errors.alphaNumeric.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Colony Name</label>
      <input type="text" formControlName="colonyName" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="locationFormGroup.controls.colonyName.errors">{{locationFormGroup.controls.colonyName.errors.alphaNumeric.message}}<br/></small>
    </div>
    <button [disabled]="!locationFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/alphaNumeric/complete/alpha-numeric-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Area Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.areaName" type="text" name="name" />
        <div v-if="locationFormGroup.controls.areaName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.areaName.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Flat Address</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.flatAddress" type="text" name="name" />
          <small class="form-text text-muted">This allowed whitespace in alpha Numeric validation<br/></small>
       <div v-if="locationFormGroup.controls.flatAddress.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.flatAddress.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Postal Address</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.postalAddress" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="locationFormGroup.controls.postalAddress.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.postalAddress.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Country Code</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.countryCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on this field then you need to add 'areaName' input as 'Delhi'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="locationFormGroup.controls.countryCode.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.countryCode.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>City Code</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.cityCode" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on this field then you need to add 'areaName' input as 'Delhi'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="locationFormGroup.controls.cityCode.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.cityCode.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Colony Name</label>
        <input id="name" class="form-control" v-model="locationFormGroup.props.colonyName" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="locationFormGroup.controls.colonyName.errors">
         <small class="form-text text-danger">{{locationFormGroup.controls.colonyName.errors.alphaNumeric.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { Location } from './location.model';

@Component
export default class AlphaNumericCompleteComponent extends Vue {
 locationFormGroup: IFormGroup<Location>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.locationFormGroup = this.formBuilder.formGroup(Location) as IFormGroup<Location>;
   }
}
</script>
