// src/assets/examples/reactive-form-validators/template-driven/validation-decorators/creditCard/messageKey/credit-card-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-creditCard-messageKey-template-driven-validation-decorators',
    templateUrl: './credit-card-message-key.component.html'
})
export class CreditCardMessageKeyTemplateDrivenValidationDecoratorsComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>Other Visa Card</label>
	    <input type="text" name="otherVisaCard" [(ngModel)]="user.otherVisaCard"  class="form-control" />

      <small class="form-text text-muted">If you want to apply conditional validation on 'Visa Card' then you need to add 'card type' input as 'Visa'.<br/></small>
      <small class="form-text text-muted">It shows custom message<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.otherVisaCard?.errors">{{userForm.controls?.otherVisaCard?.errors?.creditCard.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>American Express</label>
	    <input type="text" name="americanExpressCard" [(ngModel)]="user.americanExpressCard"  class="form-control" />

      <small class="form-text text-muted">If you want to apply conditional validation on 'American Express' then you need to add 'card type' input as 'AmericanExpress'.<br/></small>
      <small class="form-text text-muted">Message comes from Reactive Form Config<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.americanExpressCard?.errors">{{userForm.controls?.americanExpressCard?.errors?.creditCard.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Maestro Card</label>
	    <input type="text" name="maestroCard" [(ngModel)]="user.maestroCard"  class="form-control" />

      <small class="form-text text-muted">If you want to apply conditional validation on 'MaestroCard Card' then you need to add 'card type' input as 'Maestro'.<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.maestroCard?.errors">{{userForm.controls?.maestroCard?.errors?.creditCard.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>JCB Card</label>
	    <input type="text" name="jcbCard" [(ngModel)]="user.jcbCard"  class="form-control" />

      <small class="form-text text-muted">If you want to apply conditional validation on 'JCB Card' then you need to add 'card type' input as 'JCB'.<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.jcbCard?.errors">{{userForm.controls?.jcbCard?.errors?.creditCard.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Discover Card</label>
	    <input type="text" name="discoverCard" [(ngModel)]="user.discoverCard"  class="form-control" />

      <small class="form-text text-muted">If you want to apply conditional validation on 'Discover Card' then you need to add 'card type' input as 'Discover'.<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.discoverCard?.errors">{{userForm.controls?.discoverCard?.errors?.creditCard.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Master Card</label>
	    <input type="text" name="masterCard" [(ngModel)]="user.masterCard"  class="form-control" />

      <small class="form-text text-muted">If you want to apply conditional validation on 'Master Card' then you need to add 'card type' input as 'MasterCard'.<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.masterCard?.errors">{{userForm.controls?.masterCard?.errors?.creditCard.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Diners Club Card</label>
	    <input type="text" name="dinersClubCard" [(ngModel)]="user.dinersClubCard"  class="form-control" />

      <small class="form-text text-muted">If you want to apply conditional validation on 'Diners Club Card' then you need to add 'card type' input as 'DinersClub'.<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.dinersClubCard?.errors">{{userForm.controls?.dinersClubCard?.errors?.creditCard.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Other Master Card</label>
	    <input type="text" name="otherMasterCard" [(ngModel)]="user.otherMasterCard"  class="form-control" />

      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.otherMasterCard?.errors">{{userForm.controls?.otherMasterCard?.errors?.creditCard.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/creditCard/messageKey/credit-card-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Other Visa Card</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherVisaCard" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Visa Card' then you need to add 'card type' input as 'Visa'.<br/></small>
         <small class="form-text text-muted">It shows custom message<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.otherVisaCard.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherVisaCard.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>American Express</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.americanExpressCard" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'American Express' then you need to add 'card type' input as 'AmericanExpress'.<br/></small>
         <small class="form-text text-muted">Message comes from Reactive Form Config<br/></small>
       <div v-if="userFormGroup.controls.americanExpressCard.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.americanExpressCard.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Maestro Card</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.maestroCard" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'MaestroCard Card' then you need to add 'card type' input as 'Maestro'.<br/></small>
       <div v-if="userFormGroup.controls.maestroCard.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.maestroCard.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>JCB Card</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.jcbCard" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'JCB Card' then you need to add 'card type' input as 'JCB'.<br/></small>
       <div v-if="userFormGroup.controls.jcbCard.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.jcbCard.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Discover Card</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.discoverCard" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Discover Card' then you need to add 'card type' input as 'Discover'.<br/></small>
       <div v-if="userFormGroup.controls.discoverCard.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.discoverCard.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Master Card</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.masterCard" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Master Card' then you need to add 'card type' input as 'MasterCard'.<br/></small>
       <div v-if="userFormGroup.controls.masterCard.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.masterCard.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Diners Club Card</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.dinersClubCard" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Diners Club Card' then you need to add 'card type' input as 'DinersClub'.<br/></small>
       <div v-if="userFormGroup.controls.dinersClubCard.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.dinersClubCard.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Other Master Card</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherMasterCard" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.otherMasterCard.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherMasterCard.errors.creditCard.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class CreditCardMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
