// src/assets/examples/reactive-form-validators/validators/numeric/messageKey/numeric-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators ,NumericValueType} from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-numeric-messageKey-validator',
    templateUrl: './numeric-message-key.component.html'
})
export class NumericMessageKeyValidatorComponent implements OnInit {
    userInfoFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userInfoFormGroup = this.formBuilder.group({
            positiveNonDecimalNumber:['', RxwebValidators.numeric({messageKey:'numericMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userInfoFormGroup">
    <div class="form-group">
      <label>Positive Non Decimal Number</label>
      <input type="text" formControlName="positiveNonDecimalNumber" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.positiveNonDecimalNumber.errors">{{userInfoFormGroup.controls.positiveNonDecimalNumber.errors.numeric.message}}<br/></small>
    </div>
    <button [disabled]="!userInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/numeric/messageKey/numeric-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Positive Non Decimal Number</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.positiveNonDecimalNumber" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userInfoFormGroup.controls.positiveNonDecimalNumber.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.positiveNonDecimalNumber.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class NumericMessageKeyComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>
