// src/assets/examples/reactive-form-validators/template-driven/validation-directives/numeric/messageKey/numeric-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { UserInfo } from './user-info.model';

@Component({
    selector: 'app-numeric-messageKey-template-driven-validation-directives',
    templateUrl: './numeric-message-key.component.html'
})
export class NumericMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    userinfo: UserInfo
	
    constructor(
    ) { }

    ngOnInit() {
       this.userinfo= new UserInfo()
    }
}

<div>
  <form #userinfoForm = "ngForm" [rxwebForm]="userinfoForm" [model]="userinfo">
    <div class="form-group">
      <label>Positive Non Decimal Number</label>
	    <input type="text" name="positiveNonDecimalNumber" [(ngModel)]="userinfo.positiveNonDecimalNumber"  class="form-control" [rxnumeric]="{'messageKey':'numericMessageKey'}"/>

      <small class="form-text text-muted">Shows custom message based on message key<br/></small>
	   <small class="form-text text-danger" *ngIf="userinfoForm.controls?.positiveNonDecimalNumber?.errors">{{userinfoForm.controls?.positiveNonDecimalNumber?.errors?.numeric.message}}<br/></small>	
    </div>
    <button [disabled]="!userinfoForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/numeric/messageKey/numeric-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Positive Non Decimal Number</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.positiveNonDecimalNumber" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key<br/></small>
       <div v-if="userInfoFormGroup.controls.positiveNonDecimalNumber.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.positiveNonDecimalNumber.errors.numeric.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class NumericMessageKeyComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>
