// Examples/vue/rxweb-reactive-forms/src/components/odd/dynamic/odd-dynamic.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Type</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.type" type="text" name="name" />
        <div v-if="userFormGroup.controls.type.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.type.errors.odd.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.number" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Number' then you need to add 'Type' input as 'Odd'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="userFormGroup.controls.number.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.number.errors.odd.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Odd Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.oddNumber" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Odd Number' then you need to add 'Type' input as 'Odd'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="userFormGroup.controls.oddNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.oddNumber.errors.odd.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Multiples of Odd Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.multiplesOfOddNumber" type="text" name="name" />
          <small class="form-text text-muted">you can enter only an odd number<br/></small>
         <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="userFormGroup.controls.multiplesOfOddNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.multiplesOfOddNumber.errors.odd.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Other Odd Number</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherOddNumber" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.otherOddNumber.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherOddNumber.errors.odd.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class OddDynamicComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// src/assets/examples/reactive-form-validators/decorators/odd/dynamic/odd-dynamic.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from "@angular/forms"
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { RxFormBuilder } from '@rxweb/reactive-form-validators';
import { FormBuilderConfiguration,} from '@rxweb/reactive-form-validators';

import { User } from './user.model';

@Component({
    selector: 'app-odd-dynamic',
    templateUrl: './odd-dynamic.component.html'
})
export class OddDynamicComponent implements OnInit {
    userFormGroup: FormGroup

    constructor(
        private formBuilder: RxFormBuilder,private http: HttpClient    ) { }

    ngOnInit() {
        let user = new User();
        let formBuilderConfiguration = new FormBuilderConfiguration();
		this.http.get('https://rxwebioassets.blob.core.windows.net/$web/examples/reactive-form-validators/decorators/odd/dynamic/dynamic.json?v=' + environment.appVersion).subscribe(dynamic => {
            formBuilderConfiguration.dynamicValidation = JSON.parse(JSON.stringify(dynamic));
			this.userFormGroup = this.formBuilder.formGroup(user,formBuilderConfiguration);
        })
    }
}

<div>
  <form  *ngIf="userFormGroup"  [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Type</label>
      <input type="text" formControlName="type" class="form-control"   />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Number' or 'Odd Number', then you need to add 'Type' input as 'Odd'<br/></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.type.errors">{{userFormGroup.controls.type.errors.odd.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Odd Number</label>
      <input type="text" formControlName="oddNumber" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Odd Number' then you need to add 'Type' input as 'Odd'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.oddNumber.errors">{{userFormGroup.controls.oddNumber.errors.odd.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Multiples of Odd Number</label>
      <input type="text" formControlName="multiplesOfOddNumber" class="form-control"  />
      <small class="form-text text-muted">you can enter only an odd number<br/></small>
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.multiplesOfOddNumber.errors">{{userFormGroup.controls.multiplesOfOddNumber.errors.odd.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Other Odd Number</label>
      <input type="text" formControlName="otherOddNumber" class="form-control"  />
      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	<small class="form-text text-danger" *ngIf="userFormGroup.controls.otherOddNumber.errors">{{userFormGroup.controls.otherOddNumber.errors.odd.message}}<br/></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
