// src/assets/examples/reactive-form-validators/validators/grid/complete/grid-complete.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-grid-complete-validator',
    templateUrl: './grid-complete.component.html'
})
export class GridCompleteValidatorComponent implements OnInit {
    digitalInfoFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.digitalInfoFormGroup = this.formBuilder.group({
            soundRecordingGrid:['', RxwebValidators.grid()], 
            audioVisualRecordingGrid:['', RxwebValidators.grid({conditionalExpression:(x,y) => x.soundRecordingGrid == "A12425GABC1234002M" })], 
            photographGrid:['', RxwebValidators.grid({conditionalExpression:'x => x.soundRecordingGrid =="A12425GABC1234002M"' })], 
            graphicImageGrid:['', RxwebValidators.grid({message:'This is Not valid GRid' })], 
            videoGraphicGrid:['', RxwebValidators.grid({messageKey:'gridMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="digitalInfoFormGroup">
    <div class="form-group">
      <label>SoundRecording GRid</label>
      <input type="text" formControlName="soundRecordingGrid" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'AudioVisualRecording GRid' or 'Photograph GRid' then you need to add this input to 'A12425GABC1234002M'.<br/></small>
     <small class="form-text text-danger" *ngIf="digitalInfoFormGroup.controls.soundRecordingGrid.errors">{{digitalInfoFormGroup.controls.soundRecordingGrid.errors.grid.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>AudioVisualRecording GRid</label>
      <input type="text" formControlName="audioVisualRecordingGrid" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'AudioVisualRecording GRid' then you need to add 'SoundRecording GRid' field input to 'A12425GABC1234002M'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
	<small class="form-text text-danger" *ngIf="digitalInfoFormGroup.controls.audioVisualRecordingGrid.errors">{{digitalInfoFormGroup.controls.audioVisualRecordingGrid.errors.grid.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>Photograph GRid</label>
      <input type="text" formControlName="photographGrid" class="form-control"  />
      <small class="form-text text-muted">If you want to apply conditional validation on 'Photograph GRid' then you need to add 'SoundRecording GRid' field input to 'A12425GABC1234002M'.<br/></small>
      <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
	<small class="form-text text-danger" *ngIf="digitalInfoFormGroup.controls.photographGrid.errors">{{digitalInfoFormGroup.controls.photographGrid.errors.grid.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>GraphicImage GRid</label>
      <input type="text" formControlName="graphicImageGrid" class="form-control"  />
      <small class="form-text text-muted">Shows custom message.<br/></small>
	<small class="form-text text-danger" *ngIf="digitalInfoFormGroup.controls.graphicImageGrid.errors">{{digitalInfoFormGroup.controls.graphicImageGrid.errors.grid.message}}<br/></small>
    </div>
    <div class="form-group">
      <label>VideoGraphic GRid</label>
      <input type="text" formControlName="videoGraphicGrid" class="form-control"  />
      <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
	<small class="form-text text-danger" *ngIf="digitalInfoFormGroup.controls.videoGraphicGrid.errors">{{digitalInfoFormGroup.controls.videoGraphicGrid.errors.grid.message}}<br/></small>
    </div>
    <button [disabled]="!digitalInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/grid/complete/grid-complete.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>SoundRecording GRid</label>
        <input id="name" class="form-control" v-model="digitalInfoFormGroup.props.soundRecordingGrid" type="text" name="name" />
        <div v-if="digitalInfoFormGroup.controls.soundRecordingGrid.errors">
         <small class="form-text text-danger">{{digitalInfoFormGroup.controls.soundRecordingGrid.errors.grid.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>AudioVisualRecording GRid</label>
        <input id="name" class="form-control" v-model="digitalInfoFormGroup.props.audioVisualRecordingGrid" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'AudioVisualRecording GRid' then you need to add 'SoundRecording GRid' field input to 'A12425GABC1234002M'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'function'<br/></small>
       <div v-if="digitalInfoFormGroup.controls.audioVisualRecordingGrid.errors">
         <small class="form-text text-danger">{{digitalInfoFormGroup.controls.audioVisualRecordingGrid.errors.grid.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>Photograph GRid</label>
        <input id="name" class="form-control" v-model="digitalInfoFormGroup.props.photographGrid" type="text" name="name" />
          <small class="form-text text-muted">If you want to apply conditional validation on 'Photograph GRid' then you need to add 'SoundRecording GRid' field input to 'A12425GABC1234002M'.<br/></small>
         <small class="form-text text-muted">Conditional Expression with type 'string'<br/></small>
       <div v-if="digitalInfoFormGroup.controls.photographGrid.errors">
         <small class="form-text text-danger">{{digitalInfoFormGroup.controls.photographGrid.errors.grid.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>GraphicImage GRid</label>
        <input id="name" class="form-control" v-model="digitalInfoFormGroup.props.graphicImageGrid" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message.<br/></small>
       <div v-if="digitalInfoFormGroup.controls.graphicImageGrid.errors">
         <small class="form-text text-danger">{{digitalInfoFormGroup.controls.graphicImageGrid.errors.grid.message}}<br/></small>	
       </div>
      </div>  
    <div class="form-group">
        <label>VideoGraphic GRid</label>
        <input id="name" class="form-control" v-model="digitalInfoFormGroup.props.videoGraphicGrid" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message based on message key.<br/></small>
       <div v-if="digitalInfoFormGroup.controls.videoGraphicGrid.errors">
         <small class="form-text text-danger">{{digitalInfoFormGroup.controls.videoGraphicGrid.errors.grid.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { DigitalInfo } from './digitalInfo.model';

@Component
export default class GridCompleteComponent extends Vue {
 digitalInfoFormGroup: IFormGroup<DigitalInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.digitalInfoFormGroup = this.formBuilder.formGroup(DigitalInfo) as IFormGroup<DigitalInfo>;
   }
}
</script>
