// src/assets/examples/reactive-form-validators/validators/lessThan/message/less-than-message.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-lessThan-message-validator',
    templateUrl: './less-than-message.component.html'
})
export class LessThanMessageValidatorComponent implements OnInit {
    userFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userFormGroup = this.formBuilder.group({
            obtainedMarks:['',], 
            otherMarks:['', RxwebValidators.lessThan({fieldName:'obtainedMarks'  ,message:'Please enter number which is less than above field input.' })], 
        });
    }
}

<div>
  <form [formGroup]="userFormGroup">
    <div class="form-group">
      <label>Obtained Marks</label>
      <input type="text" formControlName="obtainedMarks" class="form-control" />
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.obtainedMarks.errors">{{userFormGroup.controls.obtainedMarks.errors.lessThan.message}}<br /></small>
    </div>
    <div class="form-group">
      <label>Other Marks</label>
      <input type="text" formControlName="otherMarks" class="form-control" />
      <small class="form-text text-muted">Shows custom message<br /></small>
      <small class="form-text text-danger" *ngIf="userFormGroup.controls.otherMarks.errors">{{userFormGroup.controls.otherMarks.errors.lessThan.message}}<br /></small>
    </div>
    <button [disabled]="!userFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/lessThan/message/less-than-message.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Other Marks</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.otherMarks" type="text" name="name" />
          <small class="form-text text-muted">Shows custom message<br/></small>
       <div v-if="userFormGroup.controls.otherMarks.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.otherMarks.errors.lessThan.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class LessThanMessageComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>
