// Examples/vue/rxweb-reactive-forms/src/components/endsWith/messageKey/ends-with-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Skill</label>
        <input id="name" class="form-control" v-model="userFormGroup.props.skill" type="text" name="name" />
          <small class="form-text text-muted">custom message based on messageKey<br/></small>
       <div v-if="userFormGroup.controls.skill.errors">
         <small class="form-text text-danger">{{userFormGroup.controls.skill.errors.endsWith.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { User } from './user.model';

@Component
export default class EndsWithMessageKeyComponent extends Vue {
 userFormGroup: IFormGroup<User>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userFormGroup = this.formBuilder.formGroup(User) as IFormGroup<User>;
   }
}
</script>

// Examples/angular/ExampleViewer/src/assets/examples/reactive-form-validators/template-driven/validation-directives/endsWith/messageKey/ends-with-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup,Validators } from "@angular/forms"
import { User } from './user.model';

@Component({
    selector: 'app-endsWith-messageKey-template-driven-validation-directives',
    templateUrl: './ends-with-message-key.component.html'
})
export class EndsWithMessageKeyTemplateDrivenValidationDirectivesComponent implements OnInit {
    user: User
	
    constructor(
    ) { }

    ngOnInit() {
       this.user= new User()
    }
}

<div>
  <form #userForm = "ngForm" [rxwebForm]="userForm" [model]="user">
    <div class="form-group">
      <label>Skill</label>
	    <input type="text" name="skill" [(ngModel)]="user.skill"  class="form-control" [endsWith]="{'value':'r','messageKey':'endsWithMessageKey'}"/>

      <small class="form-text text-muted">custom message based on messageKey<br/></small>
	   <small class="form-text text-danger" *ngIf="userForm.controls?.skill?.errors">{{userForm.controls?.skill?.errors?.endsWith.message}}<br/></small>	
    </div>
    <button [disabled]="!userForm.valid" class="btn btn-primary">Submit</button>
  </form>
</div>
