// src/assets/examples/reactive-form-validators/validators/image/messageKey/image-message-key.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-image-messageKey-validator',
    templateUrl: './image-message-key.component.html'
})
export class ImageMessageKeyValidatorComponent implements OnInit {
    userInfoFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.userInfoFormGroup = this.formBuilder.group({
            passport:['', RxwebValidators.image({maxHeight:100  ,maxWidth:100  ,messageKey:'imageMessageKey' })], 
        });
    }
}

<div>
  <form  [formGroup]="userInfoFormGroup">
    <div class="form-group">
      <label>Passport</label>
      <input type="file" formControlName="passport" class="form-control"  />
	<small class="form-text text-danger" *ngIf="userInfoFormGroup.controls.passport.errors">{{userInfoFormGroup.controls.passport.errors?.image?.message}}<br/></small>
    </div>
    <button [disabled]="!userInfoFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/image/messageKey/image-message-key.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Passport</label>
        <input id="name" class="form-control" v-model="userInfoFormGroup.props.passport" type="text" name="name" />
        <div v-if="userInfoFormGroup.controls.passport.errors">
         <small class="form-text text-danger">{{userInfoFormGroup.controls.passport.errors.image.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { UserInfo } from './userInfo.model';

@Component
export default class ImageMessageKeyComponent extends Vue {
 userInfoFormGroup: IFormGroup<UserInfo>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.userInfoFormGroup = this.formBuilder.formGroup(UserInfo) as IFormGroup<UserInfo>;
   }
}
</script>
