// src/assets/examples/reactive-form-validators/validators/maxTime/message/max-time-message.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from "@angular/forms"
import { RxwebValidators } from '@rxweb/reactive-form-validators';

@Component({
    selector: 'app-maxTime-message-validator',
    templateUrl: './max-time-message.component.html'
})
export class MaxTimeMessageValidatorComponent implements OnInit {
    attandanceDetailFormGroup: FormGroup

	constructor(
        private formBuilder: FormBuilder )
	{ }

    ngOnInit() {
        this.attandanceDetailFormGroup = this.formBuilder.group({
            closingTime:['', RxwebValidators.maxTime({value:'23:30' })], 
            exitTime:['', RxwebValidators.maxTime({message:'Please enter valid input'  ,fieldName:'closingTime' })], 
        });
    }
}

<div>
  <form  [formGroup]="attandanceDetailFormGroup">
    <div class="form-group">
      <label>Closing Time</label>
      <input type="text" formControlName="closingTime" class="form-control"  />
     <small class="form-text text-danger" *ngIf="attandanceDetailFormGroup.controls.closingTime.errors">{{attandanceDetailFormGroup.controls.closingTime.errors.maxTime.message}}<br/></small>	
    </div>
    <div class="form-group">
      <label>Exit Time</label>
      <input type="text" formControlName="exitTime" class="form-control"  />
      <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
     <small class="form-text text-danger" *ngIf="attandanceDetailFormGroup.controls.exitTime.errors">{{attandanceDetailFormGroup.controls.exitTime.errors.maxTime.message}}<br/></small>	
    </div>
    <button [disabled]="!attandanceDetailFormGroup.valid" class="btn btn-primary">Submit</button>
  </form>
</div>

// Examples/vue/rxweb-reactive-forms/src/components/maxTime/message/max-time-message.vue

<template>
  <div class="col-lg-12">
     <form>
       <div class="form-group">
        <label>Exit Time</label>
        <input id="name" class="form-control" v-model="attandanceDetailFormGroup.props.exitTime" type="text" name="name" />
          <small class="form-text text-muted">Shows Custom Validation Message.<br/></small>
       <div v-if="attandanceDetailFormGroup.controls.exitTime.errors">
         <small class="form-text text-danger">{{attandanceDetailFormGroup.controls.exitTime.errors.maxTime.message}}<br/></small>	
       </div>
      </div>  
       <button class="btn btn-primary">Submit</button>
     </form>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import { required,RxFormBuilder,IFormGroup } from "@rxweb/reactive-forms"
import { AttandanceDetail } from './attandanceDetail.model';

@Component
export default class MaxTimeMessageComponent extends Vue {
 attandanceDetailFormGroup: IFormGroup<AttandanceDetail>;

 formBuilder: RxFormBuilder = new RxFormBuilder();

  constructor() {
    super();
    this.attandanceDetailFormGroup = this.formBuilder.formGroup(AttandanceDetail) as IFormGroup<AttandanceDetail>;
   }
}
</script>
